client/src/main/scala/spatutorial/client/components/Heatmap.scala
Also tidied up some text alignment
=> DRT-4460 Introduce value formatter defaulting to integers

client/src/main/scala/spatutorial/client/components/Layout.scala, client/src/main/scala/spatutorial/client/components/TerminalUserDeskRecs.scala, client/src/main/scala/spatutorial/client/services/ShiftParser.scala, shared/src/main/scala/spatutorial/shared/Api.scala
- default to now for start time of IS81
- default to + 1 hour for end time
=> DRT-4469 User number input for IS81 staff

client/src/main/scala/spatutorial/client/SPAMain.scala, client/src/main/scala/spatutorial/client/components/Heatmap.scala, client/src/main/scala/spatutorial/client/components/MainMenu.scala, client/src/main/scala/spatutorial/client/components/TerminalDeployments.scala, client/src/main/scala/spatutorial/client/components/TerminalRecsPage.scala, client/src/main/scala/spatutorial/client/services/SPACircuit.scala, server/src/main/assets/stylesheets/main.less
Dropped queue desk recs
Better aligned heatmaps and table below
=> Drt 4483 drop queue reqs column

project/Settings.scala, server/src/main/scala/controllers/Application.scala, server/src/test/scala/feeds/LHRFeedSpec.scala
- Add csv parser lib rather than using regex
- reformat dates
- use airport code instead of airport for departure port
=> DRT-4505 Fix LHR csv parsing

server/src/main/protobuf/FlightsMessage.proto, server/src/main/scala/actors/FlightsActor.scala, server/src/main/scala/actors/ShiftsActor.scala, server/src/main/scala/services/SDate.scala, server/src/test/scala/controllers/FlightsActorSpec.scala, server/src/test/scala/services/ApiFlightsToProtoBufSpec.scala, shared/src/main/scala/spatutorial/shared/Api.scala
- Handle conversion from v1 strings
- Add test coverage for v1 & v2 message back to ApiFlight
=> DRT-4535 Use UTC timestamps in FlightMessage

build.sbt, server/src/main/scala/actors/CrunchActor.scala, server/src/main/scala/controllers/Application.scala, server/src/test/scala/services/CrunchTests.scala, server/src/test/scala/services/inputfeeds/StreamFlightCrunchTests.scala
- correctly specify timezone in build.sbt
- use "Europe/London" when calculating start time of crunch window
- add tests to cover expected behaviour
=> DRT-4576 Fix more timezone issues

client/src/main/scala/spatutorial/client/components/Staffing.scala, server/src/main/assets/stylesheets/main.less
- fix overlapping text area style
- fix spelling of roving
- add terminal to example fps
=> DRT-4570 Fixed point style and bugs

server/src/main/resources/logback.xml, server/src/main/scala/actors/FlightsActor.scala, server/src/main/scala/passengersplits/core/PassengerInfoRouterActor.scala, server/src/main/scala/services/CSVPassengerSplitsProvider.scala, server/src/main/scala/services/workloadcalculator/WorkloadCalculator.scala
- Add custo log level for single flights actor
- remove unnecessary logs
- reduce some logs from info to debug
=> DRT-4646 Reduce logging

server/src/main/resources/countrycodes.csv, server/src/main/scala/passengersplits/core/PassengerTypeCalculator.scala, server/src/test/scala/passengersplits/FlightPassengerQueueCalculatorSpec.scala
add country codes.csv which is a list of countries, and their 3 letter codes
from http://www.nationsonline.org/oneworld/countries_of_the_world.htm
tagged with the visanationals countries.
=> drt-4654 use visa national csv list to classify passengers

.gitignore, client/src/main/scala/drt/client/components/Heatmap.scala, client/src/main/scala/drt/client/components/TerminalComponent.scala, server/src/main/scala/actors/CrunchActor.scala, server/src/main/scala/services/ApiService.scala
Reverts UKHomeOffice/drt-scalajs-spa-exploration#172
=> Revert "Remove Terminal titles on Heatmaps"

client/src/main/scala/drt/client/components/DateTimeSelector.scala, client/src/main/scala/drt/client/components/TerminalComponent.scala, server/src/main/resources/routes, server/src/main/scala/actors/pointInTime/CrunchStateReadActor.scala, server/src/main/scala/controllers/Application.scala, server/src/main/scala/services/DesksAndQueuesCSV.scala, server/src/test/scala/services/CrunchMinutesToCSVDataTest.scala
Allow the viewing of a snapshot for any minute and allow export of desks
and queues for that snapshot.
=> DRT-4696 Export desks and queues as CSV

client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/components/TerminalDeploymentsTable.scala, client/src/main/scala/drt/client/components/TerminalDesksAndQueues.scala, client/src/test/scala/drt/client/components/FlightsTableTests.scala, server/src/main/assets/stylesheets/main.less, server/src/main/scala/services/ApiService.scala, shared/src/main/scala/spatutorial/shared/HasAirportConfig.scala
=> DRT-4761 Replace desks and queues table

client/src/main/scala/drt/client/components/DatePickerComponent.scala, client/src/main/scala/drt/client/components/SnapshotSelector.scala, client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/components/TerminalDisplayModeComponent.scala, client/src/main/scala/drt/client/services/SPACircuit.scala, server/src/main/assets/stylesheets/main.less, server/src/main/assets/stylesheets/popover-styles-staff-movement.less
- add a tab for current and snapshot
- add new date picker component
=> DRT-4767 Add date tab for snapshot and current

client/src/main/scala/drt/client/SPAMain.scala, client/src/main/scala/drt/client/components/DatePickerComponent.scala, client/src/main/scala/drt/client/components/MainMenu.scala, client/src/main/scala/drt/client/components/Navbar.scala, client/src/main/scala/drt/client/components/SnapshotSelector.scala, client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/components/TerminalDesksAndQueues.scala, client/src/main/scala/drt/client/components/TerminalDisplayModeComponent.scala
- this fixes a bug with switching between tabs
- allows users to link directly to a point in time view and any tab
=> DRT-4776 Add deep linking ability

client/src/main/scala/drt/client/SPAMain.scala, client/src/main/scala/drt/client/components/MainMenu.scala
- move dispatch call into render callback
=> DRT-4776 Fix warning on tab change

client/src/main/scala/drt/client/components/TerminalPlanningComponent.scala, client/src/test/scala/drt/client/components/PlanningTests.scala, server/src/main/scala/controllers/Application.scala
- fix set map total bug
- switch to showing 18 weeks of data
- use last sunday instead of next sunday as start date
=> DRT-4815 Forecast page bug fixes

client/src/main/scala/drt/client/components/SnapshotSelector.scala
- Sets oldest availabe date for history to 2017-11-02
=> DRT-4835 Set oldest available date for history

client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/components/TimeRangeFilter.scala
- time range filter should reflect values in state on page load
=> DRT-4838 Fix time range filter bug

client/src/main/scala/drt/client/components/DashboardTerminalSummary.scala, client/src/main/scala/drt/client/components/FlightsWithSplitsTable.scala, client/src/main/scala/drt/client/components/TerminalsDashboardPage.scala, client/src/test/scala/drt/client/components/DashboardComponentTests.scala
Previously the dashboard would not update unless the page was refreshed.
=> DRT-4847 Update timeslots on dashboard over time

server/src/main/assets/stylesheets/main.less
Add lines and alternating stripes to dashboard table
=> DRT-4878 Add lines to dashboard table

client/src/main/scala/drt/client/components/DashboardTerminalSummary.scala, server/src/main/resources/application.conf, server/src/main/scala/controllers/Application.scala
- also add forecast-export to the forecast exports
=> DRT-4902 Add portcode to export filename

client/src/main/scala/drt/client/components/DatePickerComponent.scala, client/src/main/scala/drt/client/components/SnapshotSelector.scala, client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/components/TimeRangeFilter.scala, client/src/main/scala/drt/client/services/SPACircuit.scala
- Update time range filter to default to 24 hours for days other than
today
- refactor time range component
=> DRT-4894 Adjust timerage filter defaults

client/src/main/scala/drt/client/components/FlightComponents.scala, shared/src/main/scala/spatutorial/shared/HasAirportConfig.scala
- Remove API numbers from display in chart labels
- Add human readable queue descriptions
=> DRT-4893 Remove conflicting queue numbers from chart

server/src/main/scala/controllers/Application.scala, server/src/main/scala/services/CSVData.scala, server/src/test/scala/services/crunch/CrunchMinutesToCSVDataTest.scala, server/src/test/scala/services/crunch/ForecastPlanningToCSVDataTest.scala, shared/src/main/scala/spatutorial/shared/HasAirportConfig.scala
Add configuration for export queues to airport config as some ports have
fast track and others don't.
=> DRT-4912 Configure headline export queues by port

client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/components/TerminalDisplayModeComponent.scala, shared/src/main/scala/drt/shared/HasAirportConfig.scala
Monthly Staffing & Staff Movements
=> Change Staffing Tab Names

server/src/main/scala/services/crunch/CrunchSystem.scala, server/src/main/scala/services/graphstages/ArrivalsShape.scala, server/src/main/scala/services/graphstages/Crunch.scala, server/src/main/scala/services/graphstages/ForecastCrunchShape.scala, server/src/main/scala/services/graphstages/LiveCrunchShape.scala, server/src/main/scala/services/graphstages/RunnableCrunch.scala, server/src/test/scala/services/inputfeeds/AclFeedSpec.scala
Refactoring the runnable crunch into smaller shape components
=> Drt 4957 patchy api data in front end

client/src/main/scala/drt/client/components/TerminalStaffingV2.scala, server/src/test/scala/services/ServerSDateSpec.scala, shared/src/main/scala/drt/shared/Api.scala
- adds getMonthString to SDateLike
- use month string in staffing page drop down
=> DRT-4970 Use date string on staffing page

client/src/main/scala/drt/client/services/JSDateConversions.scala, server/src/main/scala/controllers/Deskstats.scala, server/src/main/scala/drt/server/feeds/lhr/forecast/LHRForecastXLSExtractor.scala, server/src/main/scala/drt/server/feeds/lhr/forecast/LhrForecastArrivals.scala, server/src/main/scala/drt/staff/ImportStaff.scala, server/src/main/scala/services/CSVData.scala, server/src/main/scala/services/SDate.scala, server/src/main/scala/services/graphstages/Crunch.scala, server/src/main/scala/services/graphstages/StaffingStage.scala, server/src/test/scala/services/MidnightTimeZoneSpec.scala, server/src/test/scala/services/crunch/CrunchTimezoneSpec.scala, shared/src/main/scala/drt/shared/Api.scala
- convert display dates to europe/london
=> DRT-4992 Fix forecast exports for BST

server/src/main/scala/controllers/Application.scala, server/src/main/scala/services/CSVData.scala
- convert display dates to europe/london
=> DRT-4992 Fix desks & queues export for BST

server/src/main/scala/controllers/Application.scala, server/src/main/scala/services/CSVData.scala, server/src/test/scala/services/ArrivalsToCSVDataTest.scala
- convert display dates to europe/london
=> DRT-4992 Fix arrivals export for BST

client/src/main/scala/drt/client/SPAMain.scala, client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/components/DatePickerComponent.scala, client/src/main/scala/drt/client/components/SnapshotSelector.scala, client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/components/TimeRangeFilter.scala, client/src/main/scala/drt/client/services/SPACircuit.scala
Forces time range filter and terminal content to re-render (and update)
within 10 seconds of the hour changing.
=> DRT-4950 Force re-render on hour change for filter

server/src/main/scala/services/CSVData.scala, server/src/test/scala/services/ArrivalsToCSVDataTest.scala
Update arrivals export to separate out dates and times
=> DRT-4974 Move dates and times into different columns

server/src/main/scala/controllers/Application.scala, server/src/main/scala/drt/server/feeds/bhx/BHXFeed.scala, server/src/main/scala/drt/server/feeds/bhx/BHXFeedConfig.scala, server/src/main/scala/drt/server/feeds/bhx/BHXForecastFeed.scala, server/src/main/scala/drt/server/feeds/bhx/BHXLiveFeed.scala, server/src/test/scala/feeds/BHXFeedSpec.scala
Integrate the Birmingham forecast feed.
The work to call the forecast feed was done in a previous PR.
Here we are doing the calling to it.
=> Integrate the Birmingham forecast feed.

client/src/main/scala/drt/client/components/TerminalPlanningComponent.scala, client/src/test/scala/drt/client/components/PlanningTests.scala
- Fix timezone offset bug but not using midnight at the starting point
for dates, this is a bit of a hack to get the page working until we can
add MomentJs to our frontend.
- Fix CSS issues
=> DRT-5065 Fix bugs on planning page

server/src/main/scala/services/graphstages/WorkloadGraphStage.scala, server/src/test/scala/services/crunch/WorkloadGraphStageSpec.scala, shared/src/main/scala/drt/shared/HasAirportConfig.scala
- remove non-eea queue from EMA
- add queue diversion from non-eea to eea desk at EMA
=> DRT-5066 Add queue diverts to airport config

server/src/main/assets/stylesheets/main.less
I've tested this in newest version of Chrome and version 43 of Firefox but worth testing against Chrome version 43. Do you have access @richbirch ?)
=> auto field size set

client/src/main/scala/drt/client/services/SPACircuit.scala, server/src/test/scala/services/crunch/StaffMinutesSpec.scala
Added a unit test for the sum of staff movements over the same time period.
=> [DRT-5119] - Unit test for staff movements in a time period

server/src/main/scala/services/graphstages/Crunch.scala, server/src/main/scala/services/graphstages/PortStateGraphStage.scala, server/src/main/scala/services/graphstages/SimulationGraphStage.scala, server/src/main/scala/services/graphstages/StaffGraphStage.scala, server/src/test/scala/services/crunch/StaffBatchUpdateGraphStageSpec.scala, server/src/test/scala/services/crunch/StaffMinutesSpec.scala
When adding fixed points they show on the desks and queues but when removing them they still remain on the desks and queues page.
=> [DRT-5121] - We will be able to remove fixed points

server/src/main/scala/drt/server/feeds/lgw/ResponseToArrivals.scala, server/src/test/resources/lgw.xml, server/src/test/scala/feeds/LGWFeedSpec.scala
Fields changed are Actual pax, trans pax and baggage reclaim id.
=> [NIJ] - Fixes changes to the gatwick xml.

build.sbt, client/src/main/scala/drt/client/SPAMain.scala, project/Settings.scala, project/build.properties, project/plugins.sbt, server/src/main/twirl/views/index.scala.html
JIRA: https://jira.digital.homeoffice.gov.uk/browse/DRT-5126
We have updated the following libraries;
* sbt-web-scalajs-bundler
* scalaDom
* sbt
The actual changes needed to get sourcemaps working was found by @richbirch 
* `webpackBundlingMode := BundlingMode.LibraryOnly()` -> in build.sbt
* script imports in index.scala.html
Also changed some deprecated things.
=> [DRT-5126] - Get Sourcemaps working to investigate EMA bug on preprod.

build.sbt, project/Settings.scala, project/plugins.sbt
Reverts UKHomeOffice/drt-v2#483
=> Revert "[DRT-5134] - Playframework upgrade to 2.6.15"

build.sbt, project/Settings.scala, project/plugins.sbt
The play upgrade is ready to go again!
Tested in dev.
Needed to exclude xerces from the opensaml library.
=> Revert 486 revert 483 drt 5134 play upgrade

server/src/test/scala/drt/shared/AirportConfigsSpec.scala, server/src/test/scala/drt/shared/AirportConfigsSpecs.scala, server/src/test/scala/services/crunch/CrunchEgateBanksSpec.scala, server/src/test/scala/services/crunch/StaffMinutesSpec.scala, shared/src/main/scala/drt/shared/HasAirportConfig.scala
Here we have adjusted the max desks to 10 at Luton. At each hour the max desk is going to be 10.
24 corresponds to the number of hours in a day - hence I have made that assumption.
To add an EGate referral somebody at Luton will need to log in and add a `Miscellaneous Staff`.
=> DRT-5168 - Set max desks to 10 at LTN

server/src/main/scala/services/crunch/CrunchSystem.scala, shared/src/main/scala/drt/shared/HasAirportConfig.scala
Adds a new port to test LHR Nationality Based Processing times in
parallel with existing processing times
=> DRT-5181 Add lhr_nbp Airport config

e2e/cypress/integration/monthly-staffing.js, e2e/package-lock.json, e2e/package.json
Lets see if this PR fixes the issue with the monthly staffing test in jenkins.
=> DRT-5182 - Monthly staffing test fix.

client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/components/FlightsWithSplitsTable.scala, client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/services/handlers/CrunchUpdatesHandler.scala, client/src/main/scala/drt/client/services/handlers/LoaderHandler.scala, server/src/main/scala/controllers/Application.scala, server/src/main/scala/services/ApiService.scala, shared/src/main/scala/drt/shared/Api.scala
Reverts UKHomeOffice/drt-v2#552
=> Revert "Drt 5075 - Loading flights message"

client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/components/FlightsWithSplitsTable.scala, client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/services/handlers/CrunchUpdatesHandler.scala, client/src/main/scala/drt/client/services/handlers/LoaderHandler.scala, client/src/main/scala/drt/client/services/handlers/ViewModeHandler.scala, server/src/main/scala/controllers/Application.scala, server/src/main/scala/services/ApiService.scala, shared/src/main/scala/drt/shared/Api.scala
The PR is the same as before.
Just that now the spinner will appear when you move from a future day to a date before the future day.
=> Revert 554 revert 552 drt 5075 loading flights message

client/src/main/scala/drt/client/services/handlers/CrunchUpdatesHandler.scala, client/src/main/scala/drt/client/services/handlers/ViewModeHandler.scala, e2e/cypress/integration/alerts.js, e2e/cypress/integration/arrival.js, e2e/cypress/integration/staff-movements.js, e2e/package-lock.json, e2e/package.json
A possible fix for the acceptance tests running on dev.
=> DRT-5075- fix acceptance tests

client/src/main/scala/drt/client/services/handlers/ViewModeHandler.scala, e2e/cypress/integration/staff-movements.js
When changing views but viewing the same view keep the model as PendingStale as Pending empties the data.
=> DRT-5075 - fix acceptance tests for real

client/src/main/scala/drt/client/SPAMain.scala, client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/components/AlertsPage.scala, client/src/main/scala/drt/client/components/MainMenu.scala, client/src/main/scala/drt/client/services/handlers/AlertsHandler.scala, server/src/main/resources/application.conf, server/src/main/scala/controllers/Application.scala, server/src/main/scala/services/ApiService.scala, shared/src/main/scala/drt/shared/Api.scala
Create an alerts page.
When an alert is ready to be created the alerts button is enabled.
When there are alerts to delete the Delete All Alerts button is shown.
=> DRT-5239 - An Alerts page.

client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/components/AlertsComponent.scala, client/src/main/scala/drt/client/components/AlertsPage.scala, client/src/main/scala/drt/client/services/handlers/AlertsHandler.scala, e2e/cypress/integration/alerts.js, server/src/main/assets/stylesheets/main.less
- Removed Close so that the Alerts persist
- Enabled the Add Alert button
- Added validation messages on fields
- did not add bootstrap v4 to the app as it was a bit more work than this PR allowed
- removed text from date-time field once the alert is saved.
Updated Styling of the alert messages:
=> Drt 5239 alert changes

.gitignore, client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/components/Debug.scala, client/src/main/scala/drt/client/components/StaffDeploymentsAdjustmentPopover.scala, client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/components/TerminalStaffing.scala, client/src/main/scala/drt/client/services/AjaxClient.scala, client/src/main/scala/drt/client/services/SPACircuit.scala, client/src/main/scala/drt/client/services/StaffAssignmentParser.scala, client/src/main/scala/drt/client/services/handlers/FixedPointsHandler.scala, client/src/main/scala/drt/client/services/handlers/ShiftsHandler.scala, client/src/test/scala/drt/client/services/ShiftsServiceTests.scala, server/src/main/scala/actors/FixedPointsActorBase.scala, server/src/main/scala/actors/pointInTime/FixedPointsReadActor.scala, server/src/main/scala/controllers/Application.scala, server/src/main/scala/controllers/FixedPointPersistence.scala, server/src/main/scala/services/ApiService.scala, server/src/main/scala/services/graphstages/StaffGraphStage.scala, server/src/main/scala/services/graphstages/Staffing.scala, server/src/main/scala/services/staffing/StaffTimeSlots.scala, server/src/test/scala/services/staffing/FixedPointsActorSpec.scala, server/src/test/scala/services/staffing/FixedPointsAssignmentsSpec.scala, server/src/test/scala/services/staffing/StaffTimeSlotsSpec.scala, shared/src/main/scala/drt/shared/Api.scala, shared/src/main/scala/drt/shared/StaffAssignment.scala
Fixed points are now handled by StaffAssignments from the actor to the front end.
Still do to is passing them as StaffAssignments to the crunch graph
=> Drt 5033 Use StaffAssignments for fixed points rather than strings

.drone.yml, server/src/main/scala/controllers/StaffMovementsPersistence.scala
If the actor is not stopped it could cause possible memory leakage.
=> DRT-5290 - Kill actor after one time use

server/src/main/scala/actors/DrtSystem.scala, server/src/main/scala/actors/StaffMovementsActorBase.scala, server/src/main/scala/actors/pointInTime/StaffMovementsReadActor.scala, server/src/main/scala/controllers/StaffMovementsPersistence.scala, server/src/main/scala/services/graphstages/Crunch.scala, server/src/main/scala/test/TestActors.scala, server/src/main/scala/test/TestDrtSystem.scala, server/src/test/scala/actors/StaffMovementsActorSpec.scala, server/src/test/scala/services/crunch/CrunchTestLike.scala
Added expiration of expired data
Moved all DrtSystem config values into DrtConfigParameters & DrtStaticParameters for more clarity
Added tests for
- purging of expired movements
- point in time restore
=> DRT-5323 Fix point in time restore. Start purging expired data

server/src/test/scala/services/crunch/CrunchMinuteSpec.scala, server/src/test/scala/services/crunch/workload/WorkloadSpec.scala
The unit tests seem to not like comparisons between a Set and a List.
=> DRT-5349 - Fix for failing tests

client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/components/StaffAdjustmentDialogue.scala, client/src/main/scala/drt/client/components/StaffDeploymentsAdjustmentPopover.scala, client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/components/TerminalDesksAndQueues.scala, client/src/main/scala/drt/client/components/TerminalDesksAndQueuesRow.scala, client/src/main/scala/drt/client/services/SPACircuit.scala, client/src/main/scala/drt/client/services/handlers/StaffAdjustmentDialogueStateHandler.scala, client/src/main/scala/drt/client/services/handlers/StaffDeploymentAdjustmentPopoverHandler.scala
Store staff adjustment dialogue state in the RootModel to prevent it disappearing on a re-render
=> Drt 5367 fix disappearing movements dialogue

server/src/main/scala/actors/ArrivalsActor.scala, server/src/main/scala/actors/CrunchStateActor.scala, server/src/main/scala/actors/ShiftsActorBase.scala, server/src/main/scala/actors/StaffMovementsActorBase.scala, server/src/main/scala/actors/VoyageManifestsActor.scala, server/src/main/scala/actors/pointInTime/CrunchStateReadActor.scala, shared/src/main/scala/drt/shared/HasAirportConfig.scala
- to allow enough messages since the last snapshot to be restored
- Fix missing message count increment everywhere it is missing
=> DRT-5377 Increase snapshot message threshold for EMA

client/src/main/scala/drt/client/services/handlers/LoggedInStatusHandler.scala
This reverts commit 60b9c1f5a5d6c9981e9e73e710c51d139c6ae9f3.
we need a solution that doesn't reload for any uncaught exception
=> Revert "DRT-5351 Force reload if there is a redirect response"

.drone.yml
I don't know for sure if this is the fix, but it seems ok so far. We'll have to try it and see how we get on
=> Drt 5446 drone intermittant oom

server/src/main/scala/services/graphstages/ArrivalsGraphStage.scala, server/src/test/scala/controllers/ArrivalGenerator.scala, server/src/test/scala/services/crunch/ApplicationRestartSpec.scala, server/src/test/scala/services/crunch/ArrivalSplitsStageSpec.scala, server/src/test/scala/services/crunch/ArrivalsGraphStageSpec.scala, server/src/test/scala/services/crunch/FlightUpdatesTriggerNewCrunchStateSpec.scala, server/src/test/scala/services/crunch/ForecastCrunchSpec.scala, server/src/test/scala/services/inputfeeds/AclFeedSpec.scala, shared/src/main/scala/drt/shared/Api.scala
Only do a full merge of all sources on incoming base arrivals
Otherwise intelligently update according to what's changed
=> Drt 5454 optimise arrivals stage

server/src/main/scala/passengersplits/core/PassengerTypeCalculator.scala, server/src/main/scala/passengersplits/core/PassengerTypeCalculatorValues.scala, server/src/main/scala/queueus/PaxTypeAllocator.scala, server/src/main/scala/queueus/PaxTypeQueueAllocation.scala, server/src/main/scala/queueus/QueueAllocator.scala, server/src/test/scala/queues/QueueAllocationSpec.scala, shared/src/main/scala/drt/shared/HasAirportConfig.scala
Adds services to allocate pax types and queues based on configurable rules
=> DRT-5467 Add queue allocation and type allocation service

client/src/main/scala/drt/client/SPAMain.scala, client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/components/Layout.scala, client/src/main/scala/drt/client/components/PortRestrictionsModalAlert.scala, client/src/main/scala/drt/client/components/RestrictedAccessByPortPage.scala, client/src/main/scala/drt/client/services/SPACircuit.scala, client/src/main/scala/drt/client/services/handlers/ShowAlertModalDialogHandler.scala, server/src/main/resources/config/feature-flags.conf, server/src/main/scala/controllers/Application.scala, server/src/main/scala/services/ApiService.scala, shared/src/main/scala/drt/shared/Api.scala
Adds a modal warning dialog for users who do not have access to the current port
It has a feature switch
=> DRT-5494 Add modal warning about port restrictions

server/src/main/scala/manifests/passengers/BestManifests.scala, server/src/main/scala/services/OfferHandler.scala, server/src/main/scala/services/crunch/RunnableCrunch.scala, server/src/main/scala/services/graphstages/ArrivalSplitsGraphStage.scala, server/src/test/scala/drt/users/KeyCloakGroupsSpec.scala, server/src/test/scala/services/crunch/VoyageManifestsSpec.scala
- Improve performance by conflating incoming manifests when not ready for them
=> DRT-5516 Fix historic manifests source

client/src/main/scala/drt/client/SPAMain.scala, client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/services/SPACircuit.scala, client/src/main/scala/drt/client/services/handlers/UserDashboardHandler.scala
Wait for user details to be set, then populate dashboard data if required
=> DRT-5665 Add check for user type when loading dashboard

client/src/main/scala/drt/client/services/handlers/LoggedInStatusHandler.scala
=> DRT-5743 307 gives ajax exception. Reload rather than retry in this case

client/src/main/scala/drt/client/services/JSDateConversions.scala, project/Settings.scala, server/src/main/scala/services/SDate.scala, shared/src/main/scala/drt/shared/Alert.scala, shared/src/main/scala/drt/shared/Api.scala, shared/src/main/scala/drt/shared/CodeShares.scala, shared/src/main/scala/drt/shared/DesksAndQueues.scala, shared/src/main/scala/drt/shared/FeedStatus.scala, shared/src/main/scala/drt/shared/Forecast.scala, shared/src/main/scala/drt/shared/HasAirportConfig.scala, shared/src/main/scala/drt/shared/KeyCloakApi.scala, shared/src/main/scala/drt/shared/LoggedInUser.scala, shared/src/main/scala/drt/shared/SplitRatiosNs.scala, shared/src/main/scala/drt/shared/StaffAssignment.scala, shared/src/main/scala/drt/shared/StaffMovement.scala, shared/src/main/scala/drt/shared/StaffTimeSlotsForTerminalMonth.scala, shared/src/main/scala/drt/shared/splits/ApiSplitsToSplitRatio.scala, shared/src/main/scala/package.scala, sonar-project.properties
Reverts UKHomeOffice/drt-v2#749
=> Revert "Drt 5752 use drt lib as dependancy"

server/src/main/scala/actors/pointInTime/CrunchStateReadActor.scala, server/src/main/scala/controllers/Application.scala, server/src/main/scala/controllers/application/WithExports.scala
Add a wrapper function which logs a description of the request along with the time taken to execute it
Wrap all export end points in this time logging function
=> DRT-5440 Add export logs including time taken

client/src/main/scala/drt/client/components/FlightComponents.scala, server/src/main/scala/drt/server/feeds/acl/AclFeed.scala
=> DRTII-10 fix display issue for API pax nos

client/src/main/scala/drt/client/components/FlightsWithSplitsTable.scala, server/src/main/assets/stylesheets/main.less, server/src/main/scala/services/graphstages/WorkloadCalculator.scala, server/src/test/scala/services/crunch/CrunchFlightExclusionsSpec.scala, shared/src/main/scala/drt/shared/Api.scala
Also, decorate cancelled arrivals with line-through to make them stand out on the arrivals page
=> DRTII-77 Better detection of cancelled flights

client/src/main/scala/drt/client/SPAMain.scala, client/src/main/scala/drt/client/components/MainMenu.scala, client/src/main/scala/drt/client/components/TerminalComponent.scala, e2e/cypress/integration/terminal-dashboard.js
- remove TerminalDashboard feature flag
- make TerminalDashboard the default start page for all users
=> DRT-240 Make TerminalDashboard default for all users

client/src/main/scala/drt/client/components/MainMenu.scala, client/src/main/scala/drt/client/components/RestrictedAccessByPortPage.scala, e2e/cypress/integration/port-switcher.js, server/src/main/assets/stylesheets/main.less
- adds a port switcher menu item for users with access to more than 1 port
- adds a single link for users with only 2 ports
- adds a drop down menu for users with more than 2 ports
=> DRTII-260 Add port switcher

server/src/main/scala/actors/DrtSystem.scala, server/src/main/scala/actors/VoyageManifestsActor.scala, server/src/main/scala/drt/server/feeds/api/S3ApiProvider.scala, server/src/main/scala/manifests/passengers/S3ManifestPoller.scala, server/src/main/scala/services/graphstages/Crunch.scala, server/src/main/scala/test/TestActors.scala, server/src/test/scala/drt/server/feeds/api/S3ApiProviderSpec.scala
=> DRTII-269 Restrict earliest zip filename to now minus expiry millis

.gitignore, server/src/main/resources/logback.xml
- changing the timestamp format to human readable
=> Log timestamp

e2e/tests/index.d.ts
=> adding asABorderForceOfficerWithRoles chainable element

client/src/main/scala/drt/client/components/DashboardTerminalSummary.scala, server/src/main/scala/actors/MinutesActor.scala, server/src/main/scala/actors/daily/TerminalDayLikeActor.scala, server/src/main/scala/actors/daily/TerminalDayQueuesActor.scala, server/src/main/scala/actors/daily/TerminalDayStaffActor.scala, server/src/main/scala/actors/package.scala, server/src/main/scala/services/graphstages/DeploymentGraphStage.scala, server/src/main/scala/services/graphstages/LegacyDeploymentGraphStage.scala, server/src/test/scala/actors/MinutesActorSpec.scala, server/src/test/scala/actors/daily/TerminalDayQueuesActorSpec.scala, server/src/test/scala/actors/daily/TerminalDayStaffActorSpec.scala, server/src/test/scala/services/PortStateMinutesSpec.scala, shared/src/main/scala/drt/shared/Api.scala
Isolated updates to new actors &b associated code for the upcoming data storage changes
=> DRTII-60 Updates to terminal day & minute actors

server/src/main/scala/services/PaxDeltas.scala, server/src/main/scala/services/graphstages/ArrivalsGraphStage.scala, server/src/test/scala/services/crunch/ArrivalsGraphStageSpec.scala, server/src/test/scala/services/graphstages/ArrivalsGraphStagePaxNosSpec.scala
Fix case for zero ACL pax
Improve logic readability
Add comprehensive arrival pax nos tests
=> DRTII-377 Update arrival pax tests and fix zero acl case

client/src/main/scala/drt/client/components/ForecastFileUploadPage.scala, client/src/main/scala/drt/client/services/SPACircuit.scala
- Change the label from submit to upload
- adding space in button 
- Also once upload show result and once reset show upload
=> Drtii 373 improvise 1

server/src/test/scala/actors/FlightMessageConversionSpec.scala, server/src/test/scala/services/crunch/ArrivalsGraphStageSpec.scala, shared/src/main/scala/drt/shared/api/Arrival.scala
Fix conversion of arrival with a prefix to protobuf message, and improve test around arrival to message conversion
=> Drtii 383 filter suffixes consistently

server/src/main/scala/services/exports/summaries/flights/TerminalFlightsSummary.scala, server/src/test/scala/services/export/FlightsExportSpec.scala
- display None as missing value in CSV rather than 0
=> DRTII-416 Return an empty cell for csv export with missing pax count

client/src/main/scala/drt/client/services/JSDateConversions.scala, client/src/main/scala/drt/client/services/handlers/PortStateUpdatesHandler.scala, server/src/main/scala/actors/MinutesActor.scala, server/src/main/scala/actors/daily/TerminalDayLikeActor.scala, server/src/main/scala/actors/daily/TerminalDayQueuesActor.scala, server/src/main/scala/actors/daily/TerminalDayStaffActor.scala, server/src/main/scala/actors/package.scala, server/src/main/scala/services/SDate.scala, server/src/main/scala/services/graphstages/Crunch.scala, server/src/main/scala/services/graphstages/LegacyDeploymentGraphStage.scala, server/src/test/scala/actors/MinutesActorSpec.scala, server/src/test/scala/services/crunch/deskrecs/RunnableDeskRecsSpec.scala, shared/src/main/scala/drt/shared/Api.scala, shared/src/main/scala/drt/shared/PortState.scala
- Refactor dupe code
- Add UTC last midnight
- Naming improvements
=> DRTII-60 Refactor dupe code. Add UTC last midnight. Naming improvements

client/yarn.lock, server/src/main/protobuf/CrunchState.proto, server/src/main/protobuf/FlightsMessage.proto, server/src/main/scala/actors/FlightMessageConversion.scala, server/src/main/scala/actors/FlightsStateActor.scala, server/src/test/scala/actors/FlightsStateActorResponsesSpec.scala, shared/src/main/scala/drt/shared/Api.scala
A new actor to persist flights only. It'll be plugged into the new partitioned port state actor
=> Drtii 60 flights state actor

client/src/main/scala/drt/client/components/PortDashboardPage.scala, client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/components/TerminalDashboardComponent.scala, client/src/test/scala/drt/client/components/BigSummaryBoxTests.scala, client/src/test/scala/drt/client/components/PaxSplitsDisplayTests.scala, client/yarn.lock, e2e/tests/integration/api-splits.ts, server/src/main/scala/actors/DrtSystemInterface.scala, server/src/test/scala/services/ArrivalsToCSVDataTest.scala, server/src/test/scala/services/arrivals/PcpPaxSpec.scala, server/src/test/scala/services/crunch/ApiPaxNosCrunchSpec.scala, server/src/test/scala/services/crunch/PCPPaxNosSpec.scala, server/src/test/scala/services/crunch/TransferPaxInApiSpec.scala, server/src/test/scala/services/crunch/VoyageManifestsSpec.scala, server/src/test/scala/services/crunch/workload/WorkloadSpec.scala, shared/src/main/scala/drt/shared/PcpPax.scala
- remove reliance on API feature flag as now all ports have same order of precedence
- default to 0 when there are not passenger numbers rather than max pax
=> DRTII-399 Use API pax nos when there is no live pax no

server/src/main/scala/actors/summaries/FlightsSummaryActor.scala, server/src/main/scala/actors/summaries/TerminalQueuesSummaryActor.scala, server/src/main/scala/services/SDate.scala, server/src/test/scala/actors/summaries/TerminalQueuesSummaryActorSpec.scala, server/src/test/scala/services/ServerSDateSpec.scala
Add function to reliably give a Year, Month & Day for an sdate given a particular time zone
Use this function to create the right actors for the summary data
Fix the persistence id strings for the summary actors
Add tests around both areas
=> Drtii 491 fix export day for bst

server/src/main/scala/actors/DrtSystemInterface.scala, server/src/main/scala/actors/FlightsStateActor.scala, server/src/main/scala/actors/PartitionedPortStateActor.scala, server/src/main/scala/actors/daily/StreamingUpdatesLike.scala, server/src/main/scala/actors/daily/UpdatesSupervisor.scala, server/src/main/scala/test/TestActors.scala
Add names to some actors to make stacktraces easier to decipher
Handle stream shutdown in a more robust manner
=> Drtii 516 handle dead updates actors gracefully

server/src/main/scala/actors/DrtSystemInterface.scala, server/src/main/scala/actors/ProdDrtSystem.scala, server/src/main/scala/controllers/application/WithContactDetails.scala, server/src/main/scala/drt/server/feeds/bhx/BHXFeed.scala, server/src/main/scala/drt/server/feeds/lcy/LCYClient.scala, server/src/main/scala/drt/server/feeds/lcy/LCYFeed.scala, server/src/main/scala/services/OOHChecker.scala, server/src/main/scala/test/TestDrtSystem.scala, server/src/test/scala/actors/daily/TerminalDayQueuesUpdatesActorSpec.scala, server/src/test/scala/drt/server/feeds/lcy/LCYFeedSpec.scala, server/src/test/scala/feeds/bhx/BHXFeedSpec.scala, server/src/test/scala/feeds/lhr/LHRFeedSpec.scala, server/src/test/scala/services/export/DesksAndQueuesExportSpec.scala, server/src/test/scala/services/export/FlightsExportSpec.scala
Remove all new `ActorMaterializer ` creations and replace with implicits
=> Drtii 568 use implicit materializer in ooh status request

server/src/main/scala/actors/FlightsStateActor.scala, server/src/main/scala/actors/RecoveryActorLike.scala, server/src/main/scala/actors/daily/TerminalDayLikeActor.scala, server/src/main/scala/actors/pointInTime/ArrivalsReadActor.scala, server/src/main/scala/actors/pointInTime/CrunchStateReadActor.scala, server/src/main/scala/actors/pointInTime/FixedPointsReadActor.scala, server/src/main/scala/actors/pointInTime/FlightsStateReadActor.scala, server/src/main/scala/actors/pointInTime/ShiftsReadActor.scala, server/src/main/scala/actors/pointInTime/StaffMovementsReadActor.scala, server/src/main/scala/drt/server/feeds/api/S3ApiProvider.scala, server/src/main/scala/manifests/passengers/S3ManifestPoller.scala
Add logging for size of live API data being processed from zips
Reduce various chatty log messages
Add warning log message for slow actor recovery times
=> Drtii 569 log live api data size being processed

server/src/main/scala/manifests/actors/RegisteredArrivalsActor.scala, server/src/test/scala/manifests/graph/ManifestGraphSpec.scala
Address match error
Improve naming of function from `hasChanged` to `lastUpdatedHasChanged`
=> DRTII-575 Fix match error

client/src/main/scala/drt/client/components/StatusPage.scala, e2e/tests/integration/arrival-sources.ts, shared/src/main/scala/drt/shared/HasAirportConfig.scala, shared/src/main/scala/drt/shared/airportconfig/Bfs.scala, shared/src/main/scala/drt/shared/airportconfig/Bhd.scala, shared/src/main/scala/drt/shared/airportconfig/Bhx.scala, shared/src/main/scala/drt/shared/airportconfig/Brs.scala, shared/src/main/scala/drt/shared/airportconfig/Lgw.scala, shared/src/main/scala/drt/shared/airportconfig/Lhr.scala, shared/src/main/scala/drt/shared/airportconfig/Lpl.scala, shared/src/main/scala/drt/shared/airportconfig/Ncl.scala
-   Api feed to appear first in order while display
=> Drtii 14 feed sequence

client/src/main/scala/drt/client/SPAMain.scala
- fixing the config route , which was typo
=> DRTII-14 fixing typo in faq config

server/src/main/scala/drt/server/feeds/mag/MagFeed.scala, server/src/test/scala/feeds/mag/MagFeedSpec.scala
Gracefully handle exceptions caused by invalid MAG feed parameters
=> Drtii 591 catch akka http exceptions in mag feed

client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/components/ForecastFileUploadPage.scala, client/src/main/scala/drt/client/components/TooltipComponent.scala, client/src/main/scala/drt/client/services/handlers/ForecastFileUploadHandler.scala, client/yarn.lock
- Adding simple UI changes when file is uploaded so user can avoid clicking multiple time when large files get uploaded.
- Also updating misc tooltip content which was discuss . it is not related to fileupload but just content change.
=> Drtii 590 upload progress

client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/components/TooltipComponent.scala
updating pax flight and remove tooltip
=> DRTII-464 removing tooltips

e2e/tests/integration/arrivals.ts, e2e/tests/support/commands.ts
=> DRTII-464 fixing e2e test

e2e/tests/integration/arrivals.ts, e2e/tests/support/commands.ts
Reverts UKHomeOffice/drt-v2#1027
=> Revert "DRTII-464 fixing e2e test"

client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/components/TooltipComponent.scala
Reverts UKHomeOffice/drt-v2#1026
=> Revert "DRTII-464 removing tooltips"

client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/components/TerminalDashboardComponent.scala, server/src/main/scala/services/graphstages/ArrivalsGraphStage.scala, server/src/test/scala/services/crunch/ArrivalsGraphStageSpec.scala
Reverts UKHomeOffice/drt-v2#1025
=> Revert "Drtii 464"

client/src/main/scala/drt/client/SPAMain.scala, client/src/main/scala/drt/client/components/MultiDayExportComponent.scala, client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/services/SPACircuit.scala, e2e/tests/integration/api-role-access.ts, e2e/tests/integration/multi-day-export.ts, e2e/tests/integration/ui-role-access.ts, server/src/main/assets/stylesheets/main.less, server/src/main/resources/routes, server/src/main/scala/actors/DrtSystemInterface.scala, server/src/main/scala/actors/MinuteLookups.scala, server/src/main/scala/actors/ProdDrtSystem.scala, server/src/main/scala/actors/minutes/MinutesActorLike.scala, server/src/main/scala/actors/queues/DateRange.scala, server/src/main/scala/actors/queues/FlightsRouterActor.scala, server/src/main/scala/actors/queues/ManifestRouterActor.scala, server/src/main/scala/controllers/application/WithExports.scala, server/src/main/scala/controllers/application/WithSimulations.scala, server/src/main/scala/controllers/application/exports/ExportToCsv.scala, server/src/main/scala/controllers/application/exports/WithDesksExport.scala, server/src/main/scala/controllers/application/exports/WithFlightsExport.scala, server/src/main/scala/services/exports/Exports.scala, server/src/main/scala/services/exports/StreamingDesksExport.scala, server/src/main/scala/test/TestDrtSystem.scala, server/src/test/scala/actors/flights/StreamingFlightsByDaySpec.scala, server/src/test/scala/actors/minutes/MockMinutesLookup.scala, server/src/test/scala/services/crunch/ForecastPlanningToCSVDataTest.scala, server/src/test/scala/services/export/StreamingDesksExportSpec.scala, shared/src/main/scala/drt/shared/HasAirportConfig.scala, shared/src/main/scala/drt/shared/airportconfig/Lhr.scala
- refactor desks and queues export to use streaming data
- add new deployments csv endpoint
- improve urls
=> DRTII-636 Add deployments CSV export

server/src/main/scala/actors/AlertsActor.scala, server/src/main/scala/actors/ArrivalsActor.scala, server/src/main/scala/actors/daily/DayManifestActor.scala, server/src/main/scala/actors/daily/TerminalDayFlightActor.scala, server/src/main/scala/actors/daily/TerminalDayFlightUpdatesActor.scala, server/src/main/scala/actors/daily/TerminalDayQueuesActor.scala, server/src/main/scala/actors/daily/TerminalDayQueuesUpdatesActor.scala, server/src/main/scala/actors/daily/TerminalDayStaffActor.scala, server/src/main/scala/actors/daily/TerminalDayStaffUpdatesActor.scala, server/src/main/scala/actors/migration/TerminalDayCrunchMinutesMigrationActor.scala, server/src/main/scala/actors/migration/TerminalDayFlightMigrationActor.scala, server/src/main/scala/actors/migration/TerminalDayStaffMinutesMigrationActor.scala, server/src/main/scala/actors/queues/ManifestRouterActor.scala, server/src/main/scala/actors/serializers/AlertMessageConversion.scala, server/src/main/scala/actors/serializers/FlightMessageConversion.scala, server/src/main/scala/actors/serializers/ManifestMessageConversion.scala, server/src/main/scala/actors/serializers/PortStateMessageConversion.scala, server/src/main/scala/actors/serializers/ProtoBufSerializer.scala, server/src/main/scala/controllers/application/WithAlerts.scala, server/src/test/scala/actors/daily/TerminalDayFlightActorRecoverySpec.scala, server/src/test/scala/actors/serializers/AlertMessageConversionSpec.scala, server/src/test/scala/actors/serializers/FlightMessageConversionSpec.scala, server/src/test/scala/actors/serializers/ManifestMessageConversionSpec.scala, server/src/test/scala/actors/serializers/PortStateMessageConversionSpec.scala, server/src/test/scala/services/ApiFlightsToProtoBufSpec.scala
- fixes serialisation bug with alerts
- tidy up serialisation classes into the same namespace
=> DRTII-608 Fix disappearing alerts bug

server/src/main/scala/controllers/Application.scala, server/src/main/scala/services/HealthChecker.scala, server/src/test/scala/services/HealthCheckerSpec.scala
Improve implementation of health check to make test fail, and then fix incorrect logic to make it pass
=> Drtii 722 health check failure not triggering

server/src/main/scala/actors/DrtConfigParameters.scala, server/src/main/scala/actors/DrtSystemInterface.scala, server/src/main/scala/actors/ProdDrtSystem.scala, server/src/main/scala/services/crunch/CrunchSystem.scala, server/src/main/scala/services/crunch/deskrecs/RunnableDeskRecs.scala, server/src/main/scala/services/graphstages/ArrivalSplitsGraphStage.scala, server/src/main/scala/test/TestDrtSystem.scala, server/src/test/scala/manifests/queues/SplitsCalculatorSpec.scala, server/src/test/scala/services/AirportConfigSpec.scala, server/src/test/scala/services/crunch/TestConfig.scala, server/src/test/scala/services/crunch/TestDrtActor.scala, server/src/test/scala/services/graphstages/ArrivalSplitsStageSpec.scala, shared/src/main/scala/drt/shared/airportconfig/Lhr.scala
Egates off at T2 & T4
Processing times updated to reflect PLF additional times
=> Drtii 723 turn egates off at lhr

server/src/test/scala/services/AirportConfigSpec.scala, server/src/test/scala/services/graphstages/ArrivalSplitsStageSpec.scala, shared/src/main/scala/drt/shared/airportconfig/Lhr.scala
Revert egates and transaction time changes
=> DRTII-729 Roll back LHR egate and transaction time changes

server/src/main/scala/drt/server/feeds/common/XlsExtractorUtil.scala, server/src/main/scala/drt/server/feeds/lgw/LGWForecastXLSExtractor.scala, server/src/main/scala/drt/server/feeds/stn/STNForecastXLSExtractor.scala
Fixing the column type in flight number
=> DRTII-752 fixing the STN upload column type

server/src/main/scala/actors/daily/PassengersActor.scala, server/src/main/scala/services/PaxDeltas.scala, server/src/test/scala/services/PaxDeltasSpec.scala
=> DRTII-727 Cap adjustment factor to 1 to avoid inflated passengers

server/src/main/scala/controllers/Application.scala, server/src/test/scala/drt/shared/MilliTimesSpec.scala, shared/src/main/scala/drt/shared/Api.scala
Use seconds rather than minutes
=> DRTII-766 Fix healthcheck query threshold

server/src/main/scala/drt/server/feeds/ltn/LtnLiveFeed.scala, server/src/test/scala/feeds/ltn/LtnFeedSpec.scala
- use ALDT as the actual arrival field
- add test for parsing arrival json
=> DRTII-787 Update LTN feed to use new Actual field

client/src/main/scala/drt/client/components/FlightComponents.scala, client/yarn.lock, e2e/package-lock.json, e2e/tests/integration/api-splits.ts, server/src/test/scala/drt/shared/ApiFlightWithSplitsSpecs.scala, shared/src/main/scala/drt/shared/Api.scala
- 5% threshold condition for api data to show in arrivals
=> Drtii 754 ignore dodgey api data

server/src/main/scala/drt/server/feeds/ltn/LtnLiveFeed.scala, server/src/test/scala/feeds/ltn/LtnFeedSpec.scala
Reverts UKHomeOffice/drt-v2#1098
=> Revert "DRTII-787 Update LTN feed to use new Actual field"

client/yarn.lock, e2e/tests/integration/arrival-api-with-exports.ts, server/src/main/scala/services/exports/StreamingFlightsExport.scala, server/src/test/scala/services/export/StreamingFlightsExportSpec.scala
Reverts UKHomeOffice/drt-v2#1104
=> Revert "Drtii 762"

client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/components/TerminalDashboardComponent.scala, client/yarn.lock, server/src/main/scala/services/PcpArrival.scala, server/src/test/scala/drt/shared/WalkTimesSpec.scala, server/src/test/scala/services/PcpArrivalSpec.scala, shared/src/main/scala/drt/shared/DisplayMinute.scala, shared/src/main/scala/drt/shared/TimeUtil.scala, shared/src/main/scala/drt/shared/api/WalkTime.scala
small change to minute text for 0 or 1 minute
=> Drtii 759 fix minutes display

server/src/test/scala/drt/shared/ApiFlightWithSplitsSpecs.scala, shared/src/main/scala/drt/shared/Api.scala
Add comprehensive tests for different combinations of transfer pax, feed sources and api sources
=> Drtii 812 fix threshold function

client/src/main/scala/drt/client/components/Layout.scala, client/src/main/scala/drt/client/components/NegativeFeedbackComponent.scala
- update review comments for styling feedback
=> Drtii 150 review

client/src/main/scala/drt/client/components/NationalityFinderComponent.scala
Afghanistan
Sudan
Bahrain
Trinidad & Tobago
Sri Lanka
Costa Rica
Egypt
=> DRTII-835 Added 7 new countries

shared/src/main/scala/drt/shared/RedList.scala
DRTII-848 - Add Turkey to the red list
=> DRTII-848 Add Turkey to the red list

project/Settings.scala
Update drt-lib to latest version that includes the BHD role
=> Drtii 837 add bhd to deployment ports

client/src/main/scala/drt/client/components/FlightsWithSplitsTable.scala, shared/src/main/scala/drt/shared/RedList.scala
Add new countries to red list
Remove LHR's nebo pax display in favour of current red list pax based on passports
=> DRTII-855 Add new red list countries. Disable LHR nebo red list

server/src/main/scala/actors/routing/FlightsRouterActor.scala, server/src/main/scala/controllers/application/WithImports.scala, server/src/test/scala/actors/routing/FlightsRouterActorSpec.scala, server/src/test/scala/controllers/model/RedListCountsJsonFormatsSpec.scala, shared/src/main/scala/drt/shared/Api.scala, shared/src/main/scala/drt/shared/RedList.scala
Fix + test not losing red list pax on updating an arrival
Add test for parsing red list data with additional fields
=> Drtii 860 enable nebo lhr display

client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/components/TerminalContentComponent.scala, server/src/main/scala/actors/DrtSystemInterface.scala, server/src/main/scala/actors/ProdDrtSystem.scala, server/src/main/scala/test/TestDrtSystem.scala, server/src/test/scala/drt/shared/FlightDisplayFilterSpec.scala, server/src/test/scala/services/LhrRedListDatesImplSpec.scala, server/src/test/scala/services/PcpArrivalSpec.scala, shared/src/main/scala/drt/shared/FlightDisplayFilter.scala, shared/src/main/scala/drt/shared/coachTime/CoachWalkTime.scala, shared/src/main/scala/drt/shared/coachTime/DefaultCoachWalkTime.scala, shared/src/main/scala/drt/shared/coachTime/LhrCoachWalkTime.scala, shared/src/main/scala/drt/shared/redlist/LhrRedListDates.scala, shared/src/main/scala/drt/shared/redlist/LhrTerminalTypes.scala
Unify LHR red list terminal opening dates
Unify LHR red list terminal types given a date
Reinstate FlightDisplayFilter
Fix coach transfer times
Add tests for application of LHR red list coach transfer times
=> Drtii 620 red list terminal bus transfer times

server/src/main/scala/services/graphstages/ArrivalsGraphStage.scala, server/src/test/scala/services/ArrivalSpec.scala, shared/src/main/scala/drt/shared/api/Arrival.scala
Update equality function to not ignore PCP time if both are set
Add tests around expected behaviour
=> Drtii 620 send arrivals with updated pcp times

client/src/main/scala/drt/client/components/ArrivalsExportComponent.scala, client/src/main/scala/drt/client/components/TerminalPlanningComponent.scala, server/src/main/assets/stylesheets/main.less
=> Accessibility drtii 747

server/src/main/resources/config/feeds.conf, server/src/main/scala/actors/DrtConfigParameters.scala, server/src/main/scala/actors/DrtSystemInterface.scala, server/src/main/scala/drt/server/feeds/cirium/CiriumFeed.scala
Allow ACL feed to be disabled
Add cirium as live feed for PIK
Bob's your uncle
=> Drtii 873 cirium spike for pik

project/Settings.scala, server/src/main/scala/actors/daily/PassengersActor.scala, server/src/main/scala/actors/debug/DebugFlightsActor.scala, server/src/main/scala/actors/persistent/ManifestRouterActor.scala, server/src/main/scala/actors/persistent/QueueLikeActor.scala, server/src/main/scala/actors/persistent/RecoveryActorLike.scala, server/src/main/scala/actors/persistent/arrivals/ArrivalsReadActor.scala, server/src/main/scala/services/graphstages/ArrivalsGraphStage.scala
Only make adjustments to initial arrivals if the adjustment object is not a noop
=> Drtii 876 lhr continually restarting

server/src/main/resources/config/feeds.conf, server/src/main/scala/actors/DrtSystemInterface.scala, server/src/main/scala/drt/server/feeds/edi/EdiClient.scala, server/src/main/scala/drt/server/feeds/edi/EdiFeed.scala, server/src/main/scala/drt/server/feeds/edi/EdiFlightDetails.scala, server/src/test/scala/drt/server/feeds/edi/EdiFeedSpecs.scala
- ingesting new EDI feeds for live and forecast
=> Drtii 878 edi api

server/src/main/scala/actors/persistent/RedListUpdatesActor.scala, server/src/main/scala/actors/serializers/RedListUpdatesMessageConversion.scala, server/src/test/scala/actors/serializers/RedListUpdatesMessageConversionSpec.scala, shared/src/main/scala/drt/shared/Api.scala
Ensure removals are correctly serialised and deserialised
=> Drtii 892 red list changes lost on restart

project/Settings.scala, server/src/main/scala/actors/DrtSystemInterface.scala
Bump drt-lib to add HUY & DSA
Use Cirium as primary feed at HUY
=> Drtii 436 configure doncaster sheffield

e2e/tests/integration/arrival-api-with-exports.ts, project/Settings.scala, server/src/main/scala/actors/DrtSystemInterface.scala, server/src/main/scala/actors/PartitionedPortStateActor.scala, server/src/main/scala/actors/routing/FlightsRouterActor.scala, server/src/main/scala/controllers/application/WithSimulations.scala, server/src/main/scala/controllers/application/exports/WithFlightsExport.scala, server/src/main/scala/services/crunch/deskrecs/OptimisationProviders.scala, server/src/main/scala/services/exports/flights/templates/CedatFlightsExport.scala, server/src/main/scala/services/exports/flights/templates/FlightsExport.scala, server/src/main/scala/services/exports/flights/templates/FlightsWithSplitsExport.scala, server/src/main/scala/services/exports/flights/templates/FlightsWithSplitsWithActualApiExport.scala, server/src/test/scala/actors/PartitionedPortStateFunctionsSpec.scala, server/src/test/scala/actors/PartitionedPortStateTestActor.scala, server/src/test/scala/actors/flights/StreamingFlightsByDaySpec.scala, server/src/test/scala/actors/routing/FlightsRouterActorSpec.scala, server/src/test/scala/services/crunch/PortStateRequestsSpec.scala, server/src/test/scala/services/crunch/deskrecs/RunnableDeskRecsSpec.scala, server/src/test/scala/services/export/StreamingFlightsExportSpec.scala
Add nationality breakdowns to the arrivals export for users with API view privilege
Alter flight query results to also return the UtcDate for each day of results in the stream
Use the UtcDate to query for manifests to match to each day of arrivals
=> Drtii 913 full nationalities in arrivals export

server/src/main/scala/services/imports/ArrivalCrunchSimulationActor.scala
`ArrivalCrunchSimulationActor` should return Source[(UtcDate, FlightsWithSplits)]
=> DRTII-913 Fix simulations export

project/Settings.scala
- update drt port libr for cwl
=> Drtii 561 cwl

client/src/main/scala/drt/client/components/TerminalPlanningComponent.scala, server/src/main/scala/controllers/application/WithExports.scala, server/src/main/scala/services/exports/flights/templates/FlightsWithSplitsExport.scala
Show planning numbers for previous days and weeks
Remove pcp pax nos from arrival export for CTA flights
=> Drtii 925 stn accuracy query 27 31 oct 2021

server/src/main/scala/services/crunch/deskrecs/DynamicRunnableDeskRecs.scala, server/src/main/scala/services/graphstages/DynamicWorkloadCalculator.scala, server/src/test/scala/services/crunch/ArrivalsGraphStageSpec.scala, server/src/test/scala/services/crunch/deskrecs/DynamicRunnableDeskRecsSpec.scala
If live API is not trusted then add historic API
Add tests around all manifest possibilities
=> DRTII-938 Add historic & average splits if live api not trusted

server/src/main/scala/actors/ProdDrtSystem.scala
Shut actor system down before exiting
Improve shut down logs
=> DRTII-946 Sequentially call futures rather than in parallel

project/Settings.scala
- update drt lib for southampton config
=> Drtii 557 sou

project/Settings.scala
- update egate processing time
=> DRTII-932 update egate processing timings

server/src/main/resources/config/common.conf, server/src/main/scala/actors/ProdDrtSystem.scala, server/src/main/scala/controllers/Application.scala, server/src/main/scala/services/HealthChecker.scala, server/src/test/scala/services/HealthCheckerSpec.scala
Add grace period for feed health checks
=> Drtii 959 acl feed failure

e2e/tests/integration/arrival-api-with-exports.ts, server/src/main/scala/manifests/passengers/PassengerInfo.scala, server/src/main/scala/services/exports/flights/templates/FlightsWithSplitsWithActualApiExport.scala, server/src/test/scala/manifests/paxinfo/AgeRangeDataFromManifestsSpec.scala, server/src/test/scala/manifests/paxinfo/NationalityBreakdownFromManifestSpec.scala, server/src/test/scala/services/export/StreamingFlightsExportSpec.scala, shared/src/main/scala/drt/shared/api/AgeRange.scala
Add API data age range summaries to arrivals export
Update front and back end tests
Refactor some functions to optimise and tidy up
=> Drtii 953 show passenger age in arrivals export

client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/components/FlightChartComponent.scala, client/src/main/scala/drt/client/components/FlightTableRow.scala, client/src/main/scala/drt/client/components/FlightsWithSplitsTable.scala, client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/components/TerminalDashboardComponent.scala, client/src/main/scala/drt/client/components/TippyJSComponent.scala, client/src/main/scala/drt/client/services/SPACircuit.scala, client/src/main/scala/drt/client/services/handlers/PassengerInfoSummaryHandler.scala, client/src/main/scala/drt/client/services/handlers/PortStateUpdatesHandler.scala, e2e/tests/integration/api-splits.ts, server/src/main/resources/routes, server/src/main/scala/actors/DrtSystemInterface.scala, server/src/main/scala/actors/persistent/ManifestRouterActor.scala, server/src/main/scala/controllers/application/WithPassengerInfo.scala, server/src/main/scala/services/graphstages/ArrivalsGraphStage.scala
Replace touchdown model lookups with a dummy to prevent unnecessary db lookups
=> Drtii 972 lhr unstable

client/src/main/scala/drt/client/components/DaySelectorComponent.scala, client/src/main/scala/drt/client/components/MultiDayExportComponent.scala, client/src/main/scala/drt/client/components/styles/FormFieldsStyle.scala, client/src/main/scala/drt/client/util/DateUtil.scala, server/src/main/assets/stylesheets/main.less
- manually update date without error
=> DRTII-968 change date capture event to blur

client/src/main/scala/drt/client/components/FlightChartComponent.scala, client/src/main/scala/drt/client/components/Navbar.scala, server/src/main/assets/stylesheets/main.less
- few ui css changes like font , chart resize for mobile and alignments
=> Drtii 977 fix 1

client/src/main/scala/drt/client/components/EgatesScheduleEditor.scala, server/src/main/assets/stylesheets/main.less
=> Drtii 977 fix 2.1

client/src/main/scala/drt/client/components/FlightTableRow.scala, client/src/main/scala/drt/client/components/FlightsWithSplitsTable.scala
Don't show red list column when there are no red list passengers to report
=> DRTII-987 Remove red list column when no indirect red list pax

server/src/main/scala/services/graphstages/ArrivalsGraphStage.scala, server/src/test/scala/services/graphstages/ArrivalsGraphStageSpec.scala
Calculate unmatched forecast arrivals and report as metric
=> Drtii 996 monitor and alert unmatched arrivals in forecast feeds

server/src/main/scala/actors/ProdDrtSystem.scala, server/src/main/scala/services/crunch/deskrecs/DynamicRunnableDeskRecs.scala, server/src/main/scala/services/metrics/ApiValidityReporter.scala, server/src/main/scala/services/metrics/Metrics.scala, server/src/test/scala/services/crunch/deskrecs/DynamicRunnableDeskRecsSpec.scala
Record live API validity percentage for the current day
=> Drtii 992 monitor and alert for low valid api numbers

project/Settings.scala, server/src/main/scala/actors/daily/TerminalDayFlightActor.scala, server/src/main/scala/actors/persistent/arrivals/ArrivalsActor.scala, server/src/main/scala/actors/serializers/FlightMessageConversion.scala, server/src/main/scala/manifests/ManifestLookup.scala, server/src/main/scala/services/crunch/deskrecs/DynamicRunnableDeskRecs.scala, server/src/main/scala/services/graphstages/ArrivalsGraphStage.scala, server/src/test/scala/services/crunch/deskrecs/DynamicRunnableDeskRecsSpec.scala, shared/src/main/scala/drt/shared/ArrivalKey.scala
- split out to separate functions: addPax & updatePaxNos
- add test around `addPax` to prove it works
- remove a ton of debugging
=> DRTII-797 Refactor historic API pax process

server/src/main/scala/actors/daily/FlightUpdatesAndRemovals.scala, server/src/main/scala/actors/daily/StreamingUpdatesLike.scala, server/src/main/scala/actors/daily/TerminalDayFlightUpdatesActor.scala, server/src/test/scala/actors/daily/FlightUpdatesAndRemovalsSpec.scala
Move streaming flight updates and removals logic into standalone class
Add tests around new class, including bug fix
=> Drtii 1008 updates request responses contained old updates

server/src/main/scala/manifests/ManifestLookup.scala
Move common code into single function
=> DRTII-797 Refactor to reduce repetition

client/src/main/scala/drt/client/components/FlightComponents.scala, client/src/main/scala/drt/client/components/FlightTableRow.scala, server/src/main/assets/stylesheets/main.less
=> Drtii 1004 add monitor of unreceived api data

server/src/main/scala/services/crunch/deskrecs/DynamicRunnableDeskRecs.scala, server/src/test/scala/drt/shared/PaxForArrivalsTest.scala, shared/src/main/scala/drt/shared/FlightApi.scala
- Add testable object function with tests
=> DRTII-797 Extract PaxForArrivals construction

server/src/main/scala/actors/serializers/FlightMessageConversion.scala
=> DRTII-797 Tidy serialisation & deserialisation

client/src/main/scala/drt/client/components/FlightComponents.scala, e2e/tests/integration/arrivals-page.ts, server/src/main/scala/actors/serializers/FlightMessageConversion.scala, server/src/main/scala/test/controllers/TestController.scala
e2e arrivals test fixes and some tidying
=> Drtii 797 pax component fixes

server/src/main/scala/services/graphstages/ArrivalsGraphStage.scala, server/src/test/scala/services/PortStateSpec.scala, server/src/test/scala/services/crunch/ForecastCrunchSpec.scala, server/src/test/scala/services/graphstages/ArrivalsGraphStageSpec.scala
- Add all sources
- Fix tests to include all expected pax sources
=> DRTII-797 Fix merging total pax (#1278)

client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/components/StatusPage.scala, client/src/main/scala/drt/client/services/SPACircuit.scala, client/src/main/scala/drt/client/services/handlers/CrunchHandler.scala, project/Settings.scala, server/src/main/assets/stylesheets/main.less, server/src/main/resources/routes, server/src/main/scala/actors/CrunchManagerActor.scala, server/src/main/scala/actors/DrtSystemInterface.scala, server/src/main/scala/actors/daily/TerminalDayFlightActor.scala, server/src/main/scala/actors/routing/FlightsRouterActor.scala, server/src/main/scala/controllers/application/WithPortState.scala, server/src/main/scala/services/crunch/CrunchManager.scala, server/src/test/scala/actors/daily/TerminalDayFlightActorSpec.scala, shared/src/main/scala/drt/shared/FlightApi.scala
Add recrunch & recalc splits buttons to feeds page accessible by `SuperAdmin` role
Add endpoints which trigger either a simple recrunch for all forecast days, or a splits recalculation followed by a recrunch for all forecast days
=> Drtii 1044 add feature flag to force splits recalculation

client/src/main/scala/drt/client/components/ArrivalInfo.scala, client/src/main/scala/drt/client/components/FlightsWithSplitsTable.scala, client/src/main/scala/drt/client/components/StatusPage.scala, project/Settings.scala, server/src/main/scala/controllers/Application.scala
Just creating another branch with same change as rebase has messed with commits .
=> DRTII-988 change display name for cirium as live port

server/src/main/resources/countrycodes.csv
Update visa nationals list to current status
- Côte d'Ivoire -> visa
- El Salvador -> visa
- Palestinian Territory -> non-visa
=> Drtii 1055 update visa nationals list

client/src/main/scala/drt/client/modules/GoogleAnalytics.scala, server/src/main/scala/Filters.scala, server/src/main/twirl/views/index.scala.html
- move to google analytics universal to 4
=> DRTII-1053 move google analytics from universal to 4

server/src/main/scala/actors/persistent/staffing/StaffMovementsActorBase.scala, server/src/test/scala/actors/StaffMovementsActorSpec.scala
=> DRTII-1077 Fix updated millis reported when removing movement. 

server/src/main/resources/airports.dat
=> DRTII-1068 Add SZY, RMU, CDT

server/src/main/resources/config/akka.conf
Increase max header size to cope with auth-proxy (keycloak gatekeeper replacement)
=> DRTII-1082 Set play max header size via akka

project/Settings.scala, server/src/main/scala/actors/DrtSystemInterface.scala, server/src/main/scala/controllers/DrtActorSystem.scala, server/src/main/scala/controllers/application/WithAuth.scala
Add environment role check to auth function
=> DRTII-1084 Add environment check to endpoint auth

server/src/main/scala/actors/FlightLookups.scala, server/src/main/scala/actors/ProdDrtSystem.scala, server/src/main/scala/actors/daily/TerminalDayFlightActor.scala, server/src/main/scala/actors/persistent/RecoveryActorLike.scala, server/src/main/scala/test/TestActors.scala, server/src/main/scala/test/TestDrtSystem.scala, server/src/main/scala/test/TestFlightLookups.scala, server/src/main/scala/test/TestMinuteLookups.scala, server/src/test/scala/actors/PartitionedPortStateTestActor.scala, server/src/test/scala/actors/routing/FlightsRouterActorSpec.scala, server/src/test/scala/drt/server/feeds/api/ApiFeedImplTest.scala, server/src/test/scala/drt/server/feeds/lcy/LCYFeedSpec.scala, server/src/test/scala/services/crunch/ForecastCrunchSpec.scala, server/src/test/scala/services/crunch/PortStateRequestsSpec.scala, server/src/test/scala/services/crunch/StaffMinutesSpec.scala, server/src/test/scala/services/crunch/TestDrtActor.scala
=> DRTII-1095 Fix flaky tests cause. Fix slow restore logging

server/src/main/twirl/views/index.scala.html
adding token at javascript rather than relying on scala js class code
=> DRTII-1053 update gtag 

server/src/main/scala/services/crunch/deskrecs/PortDesksAndWaitsProvider.scala, server/src/main/scala/services/crunch/deskrecs/RunnableOptimisation.scala, server/src/test/scala/drt/shared/CrunchMinuteSpec.scala, server/src/test/scala/drt/shared/StaffMinuteSpec.scala, server/src/test/scala/services/crunch/deskrecs/RunnableDeskRecsSpec.scala, shared/src/main/scala/drt/shared/CrunchApi.scala, shared/src/main/scala/drt/shared/SimulationMinute.scala
Fix comparison function for `DeskRecMinute`
Add tests around comparison function for all minute classes
=> DRTII-1105 Fix DeskRecMinute comparision & add tests

client/src/main/scala/drt/client/components/FlightTableRow.scala, project/Settings.scala, server/src/test/scala/services/crunch/deskrecs/PortDesksAndWaitsProviderSpec.scala
Bump drt-lib to fix API validation
Improve val naming
=> Drtii 1104 fix identification of invalid api

client/src/main/scala/drt/client/components/Layout.scala, client/src/main/scala/drt/client/components/NegativeFeedbackComponent.scala, client/src/main/scala/drt/client/components/PositiveFeedbackComponent.scala, server/src/main/scala/controllers/application/WithEmailFeedback.scala, server/src/main/scala/email/GovNotifyEmail.scala, shared/src/main/scala/drt/shared/NegativeFeedback.scala, shared/src/main/scala/drt/shared/PositiveFeedback.scala
Improve feedback templates and tidy up code
Add user's email to the positive feedback email
Remove 'I'm happy to be contacted' from the negative feedback form & email
=> Drtii 1093 remove i would like to be contacted from negative feedback form

client/src/main/scala/drt/client/services/AjaxClient.scala, client/src/main/scala/drt/client/services/DrtApi.scala, e2e/.gitignore, e2e/cypress/e2e/api-role-access.cy.ts, e2e/cypress/e2e/arrivals-page-filter.cy.ts, e2e/cypress/e2e/monthly-staffing.cy.ts, e2e/cypress/e2e/staff-movements.cy.ts, e2e/cypress/support/commands.ts, e2e/cypress/support/index.ts, e2e/package-lock.json, e2e/package.json, e2e/tsconfig.json, server/src/main/resources/routes, server/src/main/twirl/views/index.scala.html
- Allow content security policy by play with csrf token to post , delete and put apis .  
- Ajax call to have csrf token to make api calls to server from client browser scripts.
- update csrf-token for non-browsing api used in e2e test .
=> Drtii 1132

client/src/main/scala/drt/client/services/handlers/ForecastFileUploadHandler.scala
DRTII-1132- adding csrf token while uploading file
=> DRTII-1132 csrf token while uploading file

project/Settings.scala, server/src/main/scala/services/exports/flights/templates/FlightsExport.scala, server/src/main/scala/services/exports/flights/templates/FlightsWithSplitsExport.scala, server/src/main/scala/services/exports/flights/templates/FlightsWithSplitsWithActualApiExport.scala, server/src/test/scala/services/export/StreamingFlightsExportSpec.scala
Use export headings and queue orders as defined in drt-lib
=> Drtii 1159 region export columns are not up to date

project/Settings.scala, server/src/main/scala/services/PcpArrival.scala, server/src/test/scala/services/graphstages/ArrivalsGraphStageLiveBaseArrivalsSpec.scala
DRT lib bump to fix pcp calc issue
=> DRTII-1157 Fix walk time seconds being used as chox minutes

server/src/main/scala/services/crunch/RunnableCrunch.scala, server/src/main/scala/services/graphstages/ArrivalsGraphStage.scala
=> Drtii 1157 improve walking time predictions bugfix

server/src/main/scala/drt/server/feeds/lgw/LgwForecastFeed.scala, server/src/main/scala/drt/server/feeds/lgw/LgwForecastFeedCsvParser.scala, server/src/test/scala/drt/server/feeds/lgw/LgwForecastFeedCsvParserSpec.scala, server/src/test/scala/feeds/lgw/LgwForecastFeedCsvSpec.scala
Fix LGW feed parser to expect london/europe time zone for all flights
=> Drtii 1195 lgw forecast feed not ingesting for arrivals scheduled during bst

server/src/main/resources/application-acp.conf, server/src/main/resources/application-inmemory.conf, server/src/main/resources/config/aggregate-db.conf, server/src/main/resources/config/jdbc.conf, server/src/main/scala/actors/FlightLookups.scala, server/src/main/scala/actors/daily/TerminalDayFlightActor.scala, server/src/main/scala/test/TestFlightLookups.scala, server/src/test/scala/actors/daily/TerminalDayFlightActorRecoverySpec.scala, server/src/test/scala/actors/daily/TerminalDayFlightActorSpec.scala
- restricting the arrival flight removal beyond cutoff date
=> Drtii 1187 brs

project/Settings.scala
Update drt lib get feed source name to fix the time machine pax number
=> Drtii 1225 pax

server/src/main/scala/services/graphstages/ArrivalsGraphStage.scala, server/src/test/scala/services/graphstages/ArrivalsGraphStageSpec.scala
Don't overwrite max pax with none
=> DRTII-1244 Add test for retaining MapPax figure & apply fix

client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/services/handlers/StaffMovementsHandler.scala, server/src/main/resources/routes, server/src/main/scala/actors/persistent/staffing/StaffMovementsActorBase.scala, server/src/main/scala/actors/persistent/staffing/StaffMovementsReadActor.scala, server/src/main/scala/controllers/application/WithStaffing.scala, shared/src/main/scala/drt/shared/StaffMovements.scala
Fix staff movements historic view and export
- pass date rather than point in time, and pass appropriate params to actor for expiry etc
=> Drtii 1240 drt staff movements are not retained

server/src/main/scala/controllers/application/exports/WithFlightsExport.scala, server/src/main/scala/services/exports/flights/templates/AdminExport.scala, server/src/main/scala/services/exports/flights/templates/FlightsWithSplitsExport.scala
Add predicted pax & predicted with fallback columns for super admin
=> Drtii 1258 add visibility of predicted pax to export for admins

.drone-v1.yml, client/src/main/scala/drt/client/components/Navbar.scala, server/src/main/scala/actors/DrtSystemInterface.scala, server/src/main/scala/actors/ProdDrtSystem.scala, server/src/main/scala/controllers/Application.scala, server/src/main/scala/slickdb/FeatureGuide.scala, server/src/main/scala/slickdb/FeatureGuideTable.scala, server/src/main/scala/slickdb/FeatureGuideViewRow.scala, server/src/main/scala/test/TestDrtSystem.scala
Adding FeatureGuide and FeatureGuideView Tables for test
=> Drtii 1219 1

client/src/main/scala/drt/client/components/FeatureGuideComponent.scala, client/src/main/scala/drt/client/components/Icon.scala, client/src/main/scala/drt/client/components/Navbar.scala, server/src/main/assets/stylesheets/main.less
- Using Icon for badge instead of text
=> DRTII-1219 update the badge with icon

server/src/main/scala/services/prediction/ArrivalPredictions.scala
Remove flawed logic to only update predictions every 7 days
=> Drtii 1261 turn on use of predicted passengers at selected ports

server/src/main/scala/services/ForecastAccuracyComparison.scala
=> Drtii 1261 easier forecast accuracy comparison

server/src/main/scala/actors/daily/TerminalDayFlightActor.scala
=> DRTII-1206 Only persist when diff is non-empty

.drone-v1.yml, README.md, build.sbt
Drtii 1284 -  Adding s3 cache for libraries to fetch rather than downloading from artifactory
DRTII-1265 -  set up a mirror of the NVD feed in local network to reduce the risk of rate limiting.
=> Drtii 1284 cache lib

project/Settings.scala
Update GLA config to 1 min desks & egates
=> Drtii 1296 gla is configured with high min desks

client/src/main/scala/drt/client/components/DropInComponent.scala, client/src/test/scala/drt/client/components/DropInTimeDisplayTests.scala, project/Settings.scala
Drtii 1238 display date , time and duration according to gov accessibility format
=> Drtii 1238 date format

client/src/main/scala/drt/client/components/FlightTableContent.scala
Add debugging for prod as the issue can't be reproduced locally
=> DRTII-1301 Log debugging flight & api info

client/src/main/scala/drt/client/components/FlightTableContent.scala, server/src/main/scala/services/crunch/deskrecs/DynamicRunnablePassengerLoads.scala
=> Drtii 1301 api data not matched at gla for ek0027 qf8027

project/Settings.scala, server/src/main/resources/routes, server/src/main/scala/actors/DrtSystemInterface.scala, server/src/main/scala/actors/routing/minutes/MinutesActorLike.scala, server/src/main/scala/controllers/application/AlertsController.scala, server/src/main/scala/controllers/application/HealthCheckController.scala, server/src/main/scala/providers/FlightsProvider.scala, server/src/main/scala/providers/MinutesProvider.scala, server/src/main/scala/services/HealthChecker.scala, server/src/main/scala/services/healthcheck/ApiHealthCheck.scala, server/src/main/scala/services/healthcheck/ArrivalUpdatesHealthCheck.scala, server/src/main/scala/services/healthcheck/DeskUpdatesHealthCheck.scala, server/src/main/scala/services/healthcheck/LandingTimesHealthCheck.scala, server/src/main/scala/services/healthcheck/PercentageHealthCheck.scala, server/src/test/scala/services/healthcheck/ApiHealthCheckSpec.scala, server/src/test/scala/services/healthcheck/ArrivalUpdatesHealthCheckSpec.scala, server/src/test/scala/services/healthcheck/DeskUpdatesHealthCheckSpec.scala, server/src/test/scala/services/healthcheck/LandingTimesHealthCheckSpec.scala, shared/src/main/scala/drt/shared/CodeShares.scala
Add endpoints for:
- Missing API for landed flights
- Missing landing times for arrivals scheduled in the past
- Missing updates for arrivals due soon
- Missing desk recommendations after flight updates
=> Drtii 1305 alerting on incidents

client/src/main/scala/drt/client/components/ContactPage.scala, server/src/main/scala/controllers/application/AuthController.scala, server/src/main/scala/slickdb/Tables.scala, server/src/main/scala/slickdb/UserTable.scala, server/src/main/scala/test/TestDrtSystem.scala
- Adding new columns for user drop_in_notification_at and created_at
- creating a deep link for drt email on contact us page
=> Drtii 1224

database_setup/aggregated-user.sql
House keeping - updating the schema to what it currently is
=> DRTII-1305 update schema creation

server/src/main/scala/controllers/application/DropInsController.scala, server/src/main/scala/controllers/application/EmailNotificationController.scala, server/src/main/scala/module/DRTModule.scala
- Providing Gov Notify instance from Module as DI for drop-in notification
=> DRTII-1337 provide gov notification instance

.drone-v1.yml, project/Settings.scala, project/build.properties, server/src/main/resources/routes, server/src/main/scala/controllers/application/RedListsController.scala
Update drt-lib
Remove redlist edit routes
=> DRTII-1305 Remove redlist admin routes. Upgrade drt-lib

client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/components/TerminalPlanningComponent.scala, client/src/main/scala/drt/client/services/handlers/ForecastHandler.scala
Parse an `Option` as sent by response
=> DRTII-1344 Parse Option

.drone-v1.yml, project/Settings.scala, project/build.properties, project/plugins.sbt, sonar-project.properties
Upgrade drt-lib
Fix drone steps to run analysis reliably & improve naming
=> Drtii 1343 upgrade spark library

project/Settings.scala
=> Drtii 1354 peru showing on red list

client/src/main/scala/drt/client/components/ContactPage.scala, client/src/main/scala/drt/client/components/Layout.scala
- Review comments from Rob mentioned in origin DRTII-1316
=> DRTII-1316 Rob review comments

client/src/main/scala/drt/client/components/FeatureGuideComponent.scala, server/src/main/assets/stylesheets/flickity.css
- Fixing the New Feature dialog box styling
=> DRTII-1380 fixing New feature style

server/src/main/scala/actors/DrtStaticParameters.scala, server/src/main/scala/actors/persistent/staffing/ShiftsActor.scala, server/src/main/scala/actors/persistent/staffing/ShiftsReadActor.scala, server/src/main/scala/uk/gov/homeoffice/drt/crunchsystem/DrtSystemInterface.scala, server/src/main/scala/uk/gov/homeoffice/drt/crunchsystem/ProdPersistentStateActors.scala, server/src/main/scala/uk/gov/homeoffice/drt/testsystem/crunchsystem/TestPersistentStateActors.scala, server/src/test/scala/actors/DrtStaticParametersSpec.scala, server/src/test/scala/actors/ShiftsActorSpec.scala, server/src/test/scala/services/crunch/CrunchTestLike.scala, server/src/test/scala/services/crunch/TestDrtActor.scala
Add tests around untested time functions
Add test for persistence & restore of shifts snapshots
Add more logging for persistence & recovery of shifts snapshots
=> Drtii 1382 lhr staffing numbers disappearing

server/src/main/resources/routes
Remove CSRF check on end point so it can be accessed directed
=> Drtii 1392 re populate live pax end point is not accessible in preprod or prod

server/src/main/resources/routes, server/src/main/scala/controllers/application/PortStateController.scala, server/src/main/scala/controllers/application/SummariesController.scala, server/src/main/scala/services/crunch/deskrecs/DynamicRunnableDeskRecs.scala, server/src/main/scala/services/crunch/deskrecs/DynamicRunnablePassengerLoads.scala, server/src/main/scala/services/scenarios/Scenarios.scala, server/src/main/scala/uk/gov/homeoffice/drt/crunchsystem/DrtSystemInterface.scala, server/src/test/scala/controllers/application/SummariesControllerSpec.scala, server/src/test/scala/services/crunch/TestDrtActor.scala, server/src/test/scala/services/crunch/deskrecs/DynamicRunnableDeskRecsSpec.scala, server/src/test/scala/services/crunch/deskrecs/RunnableDeskRecsSpec.scala
Add end point to recrunch date range
Add missing auth around pax summaries end points
Update tests to add auth
=> Drtii 1394 add end point to re crunch a date range

client/src/main/scala/drt/client/components/FeatureGuideComponent.scala, server/src/main/assets/stylesheets/flickity.css, server/src/main/resources/routes
Drtii 1400 : fixing style for What's New Feature dialog
=> Drtii 1400 new feature

project/Settings.scala, server/src/main/scala/controllers/application/SummariesController.scala
Flip content type check so that json is default when it's not specified
=> Drtii 1405 add dashboard app proxy to port passengers endpoint

project/Settings.scala, server/src/test/scala/services/prediction/ArrivalPredictionsSpec.scala
=> DRTII-1412 Update drt-lib

project/Settings.scala, server/src/main/scala/controllers/application/SummariesController.scala, server/src/main/scala/uk/gov/homeoffice/drt/crunchsystem/ProdPersistentStateActors.scala, server/src/test/scala/controllers/application/SummariesControllerSpec.scala
Move passenger summaries and json format to drt-lib
=> Drtii 1411 adjust pax summaries end point

client/src/main/scala/drt/client/components/ApiStatusComponent.scala, client/src/main/scala/drt/client/components/FlightTableRow.scala, client/src/main/scala/drt/client/components/Layout.scala, client/src/test/scala/drt/client/components/ApiFeedStatusTest.scala, server/src/main/resources/config/feature-flags.conf, server/src/main/resources/routes, server/src/main/scala/controllers/Application.scala, server/src/main/scala/controllers/DrtActorSystem.scala, server/src/main/scala/controllers/application/ForecastAccuracyController.scala, server/src/main/scala/providers/FlightsProvider.scala, server/src/main/scala/services/PcpArrival.scala, server/src/main/scala/uk/gov/homeoffice/drt/crunchsystem/DrtSystemInterface.scala, server/src/test/scala/controllers/application/ForecastAccuracyControllerSpec.scala, server/src/test/scala/services/graphstages/ArrivalsGraphStageEdiSpec.scala, server/src/test/scala/services/graphstages/ArrivalsGraphStageLiveBaseArrivalsSpec.scala, server/src/test/scala/services/graphstages/ArrivalsGraphStageSpec.scala
End point to compare daily ml pax predictions against the regular pax forecast 
Test for expected output
=> Drtii 1412 add forecast model comparison endpoint

server/src/main/scala/controllers/application/ForecastAccuracyController.scala
Include Api for actual pax nos
=> DRTII-1412 Including Api feed for actual pax nos as fallback

server/src/main/scala/controllers/application/HealthCheckController.scala, server/src/main/scala/services/healthcheck/PercentageHealthCheck.scala, server/src/main/scala/uk/gov/homeoffice/drt/crunchsystem/DrtSystemInterface.scala, server/src/main/scala/uk/gov/homeoffice/drt/service/ApplicationService.scala, server/src/test/scala/controllers/application/HealthCheckControllerSpec.scala
Fix order or start & end. Add controller test
=> DRTII-1424 Fix order or start & end. Add controller test

server/src/main/scala/services/HealthChecker.scala, server/src/test/scala/services/healthcheck/LandingTimesHealthCheckSpec.scala
Fix incorrect mapTo for feed source statuses
=> DRTII-1424 Fix mapTo

server/src/main/resources/routes, server/src/main/scala/controllers/application/HealthCheckController.scala, server/src/test/scala/controllers/application/HealthCheckControllerSpec.scala
Adjust end points to be more flexible
=> DRTII-1426 Replace minutes with start & end times

client/src/main/scala/drt/client/components/FlightTableContent.scala
No flights to display when there are no flights
=> Display info message if not flight data

client/src/main/scala/drt/client/components/FeatureGuideComponent.scala, client/src/main/scala/drt/client/components/ReactMarkdown.scala, project/Settings.scala
- Supporting image in feature guide
=> Drtii 1438 image feature

client/src/main/scala/drt/client/components/AlertsComponent.scala, client/src/main/scala/drt/client/components/Layout.scala, client/src/main/scala/drt/client/components/Navbar.scala, e2e/cypress/e2e/contact-page.cy.ts, server/src/main/assets/stylesheets/main.less
- Removing contact us page and adding email on top
=> Drtii 1397 remove contact us

server/src/main/scala/module/DRTModule.scala, server/src/test/scala/controllers/application/ExportPortConfigControllerSpec.scala, server/src/test/scala/controllers/application/FeatureFlagsControllerSpec.scala, server/src/test/scala/controllers/application/WalkTimeControllerSpec.scala
=> drtParams to be lazy initialisation

server/src/main/scala/controllers/application/ExportPortConfigController.scala, server/src/main/scala/uk/gov/homeoffice/drt/service/ApplicationService.scala, server/src/test/scala/controllers/application/ExportPortConfigControllerSpec.scala
Update default empty state for SlaConfig actor
Tidy naming & redundant functions
Remove extraneous white space
=> Drtii 1469 fix failing config export test

server/src/main/scala/uk/gov/homeoffice/drt/service/ApplicationService.scala
=> DRTII-1468 Restore updated pax model

client/src/main/scala/drt/client/components/FlightTable.scala
- Adding 5 seconds delay for sending latest flight search value for analytics
=> Drtii 1437 analytics

client/src/main/scala/drt/client/SPAMain.scala, client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/components/FlightTable.scala, client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/components/TerminalPlanningComponent.scala, client/src/main/scala/drt/client/services/DrtApi.scala, client/src/main/scala/drt/client/services/SPACircuit.scala, client/src/main/scala/drt/client/services/handlers/ForecastHandler.scala, client/src/main/scala/drt/client/services/handlers/UserPreferencesHandler.scala, client/src/main/scala/drt/client/services/handlers/UserSelectionPlanningPeriodHandler.scala, client/src/main/scala/drt/client/services/handlers/UserStaffPlanningHandler.scala, database_setup/aggregated-user.sql, e2e/cypress/e2e/planning.cy.ts, server/src/main/assets/stylesheets/main.less, server/src/main/resources/routes, server/src/main/scala/controllers/Application.scala, server/src/main/scala/controllers/application/AuthController.scala, server/src/main/scala/controllers/application/ExportsController.scala, server/src/main/scala/controllers/application/PortStateController.scala, server/src/main/scala/services/exports/Forecast.scala, server/src/main/scala/slickdb/Tables.scala, server/src/main/scala/slickdb/UserTable.scala, server/src/main/scala/uk/gov/homeoffice/drt/testsystem/TestTables.scala
- User to select the time period intervals for staff planning and recommendation 
- Also to keep track of user selection
=> Drtii 1409 planning

server/src/main/resources/config/feature-flags.conf, server/src/main/scala/actors/ProdDrtParameters.scala, server/src/main/scala/uk/gov/homeoffice/drt/service/ApplicationService.scala, server/src/main/scala/uk/gov/homeoffice/drt/testsystem/TestTables.scala
Add feature flag to enable retention policy deletion
Disabled by default
=> DRTII-1439 Feature flag for data retention policy

Dockerfile, server/src/main/resources/application-acp.conf, server/src/main/resources/application-inmemory.conf, server/src/main/resources/config/common.conf, server/src/main/resources/config/jdbc.conf, server/src/main/resources/postgres.conf
Set postgres connection to `verify-full` to check the certificate chain and verify the host name matches the certificate
Update certificate to AWS's most recent
Tidy up configuration files
=> Drtii 1497 update rds certs

client/src/main/scala/drt/client/components/FlightTable.scala, client/src/main/scala/drt/client/components/FlightTableContent.scala, client/src/main/scala/drt/client/services/handlers/AirportCountryHandler.scala
Adding country and origin for flight filtering
=> Adding fight filter for country and origin

project/Settings.scala, server/src/main/scala/controllers/application/ForecastAccuracyController.scala, server/src/main/scala/providers/FlightsProvider.scala, server/src/main/scala/uk/gov/homeoffice/drt/service/ApplicationService.scala, server/src/test/scala/controllers/application/ForecastAccuracyControllerSpec.scala, server/src/test/scala/services/prediction/ArrivalPredictionsSpec.scala
2 fixes:
- use model from 3 days before date in question (for forecast)
- use forecast arrival data from 3 days before date in question (for forecast)
=> Drtii 1508 use appropriate model version in comparison end point

server/src/main/scala/controllers/application/SimulationsController.scala, server/src/main/scala/controllers/application/StaffingController.scala, server/src/main/scala/controllers/application/SummariesController.scala, server/src/main/scala/controllers/application/exports/CsvFileStreaming.scala, server/src/main/scala/controllers/application/exports/DesksExportController.scala, server/src/main/scala/controllers/application/exports/FlightsExportController.scala
Fix streaming downloads - use `.Stream` rather than `.Chunked`...
Refactor to tidy
=> DRTII-1508 Fix streaming

client/src/main/scala/drt/client/components/Navbar.scala, server/src/main/resources/routes, server/src/main/scala/api/KeyCloakAuth.scala, server/src/main/scala/controllers/Application.scala, server/src/main/scala/controllers/application/ABFeatureController.scala, server/src/main/scala/controllers/application/AuthController.scala, server/src/main/scala/controllers/application/DropInsController.scala, server/src/main/scala/controllers/application/ExportsController.scala, server/src/main/scala/controllers/application/UserFeedbackController.scala, server/src/main/scala/uk/gov/homeoffice/drt/routes/UserRoleProviderLike.scala, server/src/main/twirl/views/index.scala.html, server/src/test/scala/controllers/application/AirportInfoControllerSpec.scala, server/src/test/scala/controllers/application/AlertsControllerSpec.scala, server/src/test/scala/controllers/application/AuthControllerSpec.scala, server/src/test/scala/controllers/application/ContactDetailsControllerSpec.scala, server/src/test/scala/controllers/application/DataRetentionControllerSpec.scala, server/src/test/scala/controllers/application/DropInsControllerSpec.scala, server/src/test/scala/controllers/application/EgateBanksControllerSpec.scala, server/src/test/scala/controllers/application/FeatureFlagsControllerSpec.scala, server/src/test/scala/controllers/application/FeedsControllerSpec.scala, server/src/test/scala/controllers/application/ForecastAccuracyControllerSpec.scala, server/src/test/scala/controllers/application/HealthCheckControllerSpec.scala, server/src/test/scala/controllers/application/StaffingControllerSpec.scala, server/src/test/scala/controllers/application/SummariesControllerSpec.scala, server/src/test/scala/controllers/application/WalkTimeControllerSpec.scala, server/src/test/scala/controllers/application/exports/FlightsExportControllerSpec.scala
- Upgrading to Oauth proxy and changing the header required for the proxy
=> Drtii 1082 oauth proxy

project/Settings.scala, server/src/main/assets/stylesheets/main.less, server/src/main/scala/controllers/application/ForecastAccuracyController.scala
Update drt-lib. Filter codeshares
=> DRTII-1510 Update drt-lib. Filter codeshares

client/src/main/scala/drt/client/components/FlightTableContent.scala, e2e/cypress/e2e/arrival-api-with-exports.cy.ts, project/Settings.scala, server/src/main/scala/actors/persistent/arrivals/AclForecastArrivalsActor.scala, server/src/main/scala/actors/persistent/arrivals/ArrivalsActor.scala, server/src/main/scala/controllers/application/SummariesController.scala, server/src/main/scala/controllers/application/exports/FlightsExportController.scala, server/src/main/scala/passengersplits/WholePassengerQueueSplits.scala, server/src/main/scala/services/crunch/deskrecs/DynamicRunnablePassengerLoads.scala, server/src/main/scala/services/exports/FlightExports.scala, server/src/main/scala/services/exports/GeneralExport.scala, server/src/main/scala/services/liveviews/PassengersLiveView.scala, server/src/main/scala/services/scenarios/Scenarios.scala, server/src/main/scala/uk/gov/homeoffice/drt/service/ApplicationService.scala, server/src/test/scala/controllers/application/SummariesControllerSpec.scala, server/src/test/scala/controllers/application/exports/FlightsExportControllerSpec.scala, server/src/test/scala/services/CodeSharesSpec.scala, server/src/test/scala/services/crunch/TestDrtActor.scala, server/src/test/scala/services/crunch/deskrecs/DynamicRunnableDeskRecsSpec.scala, server/src/test/scala/services/crunch/deskrecs/RunnableDeskRecsSpec.scala, server/src/test/scala/services/exports/FlightExportsSpec.scala, server/src/test/scala/services/exports/StreamingFlightsExportSpec.scala, server/src/test/scala/services/liveviews/PassengersLiveViewTest.scala, shared/src/main/scala/drt/shared/CodeShares.scala
Populate capacity by terminal and date
Add capacity to port, terminal & flight level export APIs
=> Drtii 1509 add total capacity to download manager exports

client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/components/FeedsStatusPage.scala, client/src/main/scala/drt/client/components/TerminalDesksAndQueues.scala, client/src/main/scala/drt/client/services/handlers/AppControlHandler.scala, server/src/main/scala/actors/CrunchManagerActor.scala, server/src/main/scala/controllers/application/PortStateController.scala, server/src/main/scala/services/crunch/CrunchSystem.scala, server/src/main/scala/services/crunch/deskrecs/DynamicRunnablePassengerLoads.scala, server/src/main/scala/services/crunch/deskrecs/PortDesksAndWaitsProvider.scala, server/src/main/scala/uk/gov/homeoffice/drt/service/ApplicationService.scala, server/src/test/scala/services/crunch/TestDrtActor.scala
Add super-admin re-crunch button to desks and queues tab
=> Drtii 1524 sla breach at bhx with excess staff

server/src/main/resources/routes, server/src/main/scala/controllers/application/SummariesController.scala, server/src/test/scala/controllers/application/SummariesControllerSpec.scala
Reinstate pax endpoints so the download manager can still use them
=> DRTII-1543 Reinstate pax endpoints

client/src/main/scala/drt/client/components/FlightTableRow.scala
Fixing the logic of showing highted flights when `Only highlight flights with all selected info` option is selected
=> Drtii 1511 flight filter react 2

client/src/main/scala/drt/client/components/ArrivalInfo.scala, client/src/main/scala/drt/client/components/FlightTableComponents.scala, client/src/main/scala/drt/client/components/FlightTableContent.scala, client/src/main/scala/drt/client/components/FlightTableRow.scala, e2e/cypress/e2e/arrival-api-with-exports.cy.ts, e2e/cypress/support/commands.ts, project/Settings.scala, server/src/main/scala/controllers/application/DebugController.scala, server/src/test/scala/controllers/application/exports/FlightsExportControllerSpec.scala, server/src/test/scala/drt/server/feeds/lcy/LCYFlightTransformSpec.scala, server/src/test/scala/drt/shared/PcpUtilsSpec.scala, server/src/test/scala/feeds/cirium/CiriumFeedSpec.scala, server/src/test/scala/services/PcpArrivalSpec.scala, server/src/test/scala/services/arrivals/ArrivalDataSanitiserSpec.scala, server/src/test/scala/services/exports/StreamingFlightsExportSpec.scala, server/src/test/scala/slickdb/AggregatedDaoSpec.scala
=> Drtii 1545 chocks

client/src/main/scala/drt/client/components/FlightHighlighter.scala, client/src/main/scala/drt/client/components/FlightTable.scala, client/src/main/scala/drt/client/components/FlightTableContent.scala, client/src/main/scala/drt/client/components/FlightTableRow.scala, client/src/main/scala/drt/client/components/styles/DrtTheme.scala
- refactor highlighted flight 
- fixing the color text of the selected text box of highlight option
=> Drtii 1443 pax color

server/src/main/twirl/views/index.scala.html
- Adding consent in gtag which will prevent warning in google analytics
=> adding gtag consent

client/package-lock.json, client/src/main/scala/drt/client/components/FlightFlaggerFilters.scala, client/src/main/scala/drt/client/components/FlightTable.scala, client/src/main/scala/drt/client/components/FlightTableContent.scala, project/Settings.scala, shared/src/main/scala/drt/shared/SimulationParams.scala
Update to latest drt-react release
Fix flight counts bug & improve formatting
=> Drtii 1572 hide show flights options until flights are highlighted

client/src/main/scala/drt/client/components/FlightTableRow.scala, client/src/main/scala/drt/client/components/TerminalContentComponent.scala
Apply abbr tag to origins without descriptions
Only apply def tag when we have the airport info available
=> DRTII-1544 Only apply abr & def to known origins with additional info

server/src/main/scala/actors/daily/RequestAndTerminateActor.scala, server/src/main/scala/actors/persistent/staffing/ShiftsActor.scala, server/src/main/scala/actors/routing/SequentialWritesActor.scala, server/src/main/scala/actors/routing/minutes/MinutesActorLike.scala, server/src/main/scala/uk/gov/homeoffice/drt/service/ApplicationService.scala, server/src/test/scala/actors/ShiftsActorSpec.scala
Reimplement sub-optimal algorithms to update shifts.
Now takes a few milliseconds to update 6 months rather than tens of seconds
=> DRTII-1579 Optimise shift updates function

server/src/main/scala/drt/server/feeds/ltn/LtnLiveFeed.scala, server/src/test/scala/feeds/ltn/LtnFeedSpec.scala
Tidy flights response code
Add body of non-200 responses to log message
=> Drtii 1595 ltn live feed

client/src/main/scala/drt/client/SPAMain.scala, client/src/main/scala/drt/client/components/FeedsStatusPage.scala, client/src/main/scala/drt/client/components/FlightTableContent.scala, client/src/main/scala/drt/client/components/ForecastUploadComponent.scala, client/src/main/scala/drt/client/components/MonthlyStaffing.scala, client/src/main/scala/drt/client/components/PortConfigPage.scala, client/src/main/scala/drt/client/components/PortDashboardPage.scala, client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/components/TerminalDashboardComponent.scala, client/src/main/scala/drt/client/components/TerminalDesksAndQueues.scala, client/src/main/scala/drt/client/components/TerminalPlanningComponent.scala, client/src/main/scala/drt/client/components/TerminalStaffing.scala, client/src/main/scala/drt/client/components/TrainingHubComponent.scala, client/src/main/scala/drt/client/components/UserDashboardPage.scala, client/src/main/scala/drt/client/components/scenarios/ScenarioSimulationComponent.scala, project/Settings.scala, server/src/main/scala/controllers/Application.scala, shared/src/main/scala/drt/shared/airportconfig/Test.scala, shared/src/main/scala/drt/shared/airportconfig/Test2.scala
Add page titles to each section in DRT
=> Drtii 696 duplicated non descriptive page titles

client/src/main/scala/drt/client/components/MonthlyStaffing.scala, client/src/main/scala/drt/client/services/handlers/ShiftsHandler.scala, server/src/main/scala/actors/persistent/staffing/ShiftsActor.scala, server/src/main/scala/controllers/application/StaffingController.scala, server/src/main/scala/uk/gov/homeoffice/drt/service/staffing/ShiftsService.scala, server/src/main/scala/uk/gov/homeoffice/drt/service/staffing/ShiftsServiceImpl.scala
=> DRTII-1603 Return all shifts on update

client/package-lock.json, server/src/main/scala/services/crunch/deskrecs/DynamicRunnableDeskRecs.scala, server/src/main/scala/services/crunch/deskrecs/DynamicRunnablePassengerLoads.scala, server/src/main/scala/services/crunch/deskrecs/PortDesksAndWaitsProvider.scala, server/src/test/scala/services/crunch/deskrecs/DynamicRunnableDeskRecsSpec.scala, server/src/test/scala/services/crunch/deskrecs/DynamicRunnablePassengerLoadsSpec.scala
Reinstate hourly pax table updates on new pax load calculations
Add test to ensure update function is executed
=> Drtii 1673 no hourly pax data from late december 2024

client/package-lock.json, client/src/main/scala/drt/client/components/MonthlyStaffing.scala, client/src/main/scala/drt/client/components/UpdateStaffForTimeRangeForm.scala, client/src/main/scala/drt/client/util/DateRange.scala, project/Settings.scala
Fix date & time of staff assignments
=> Drtii 1681 min staff handle edits

client/package-lock.json, client/src/main/scala/drt/client/components/TrainingMaterialComponent.scala, client/src/main/scala/drt/client/components/UpdateStaffForTimeRangeForm.scala, client/src/main/scala/drt/client/components/scenarios/SimulationChartComponent.scala, project/Settings.scala, server/src/main/scala/actors/persistent/staffing/ShiftsReadActor.scala, server/src/main/scala/services/liveviews/FlightsLiveView.scala, server/src/main/scala/services/liveviews/QueuesLiveView.scala, server/src/main/scala/uk/gov/homeoffice/drt/crunchsystem/DrtSystemInterface.scala, server/src/test/scala/services/crunch/TestDrtActor.scala
Add error logging for failed insert queries
Update drt-lib to use master build
Fix some naming..
=> Drtii 1684 container restarts in kubernetes

client/package-lock.json, client/src/main/scala/drt/client/components/AccessibilityStatementComponent.scala, client/src/main/scala/drt/client/components/BottomBarComponent.scala, project/Settings.scala
rename url to accessibilityStatementUrl and update drt react version to 1.6.3
=> Drtii 1574 react api change

server/src/main/assets/stylesheets/main.less
overflow auto for footer to stay at bottom
=> adding main-content to overflow auto

server/src/main/assets/stylesheets/main.less
420 looks better than 300 px default height for staffing table
=> Drtii 1574 desk queue 1

project/Settings.scala, server/src/main/scala/drt/server/feeds/acl/AclFeed.scala
Update drt-lib to include ACL for SEN
=> Drtii 1700 add acl to sen

project/Settings.scala, server/src/main/resources/config/feeds.conf, server/src/main/scala/actors/ProdDrtParameters.scala, server/src/main/scala/drt/server/feeds/bhx/BHXFeed.scala, server/src/main/scala/drt/server/feeds/cwl/CWLFeed.scala, server/src/main/scala/uk/gov/homeoffice/drt/service/ProdFeedService.scala, server/src/main/scala/uk/gov/homeoffice/drt/testsystem/TestTables.scala, server/src/test/scala/feeds/cwl/CWLFeedSpec.scala
Add CWL SOAP based live feed + tests
=> Drtii 1706 spike implement cwl live feed

client/src/main/scala/drt/client/SPAMain.scala, client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/components/MonthlyShifts.scala, client/src/main/scala/drt/client/components/MonthlyShiftsUtil.scala, client/src/main/scala/drt/client/components/MonthlyStaffing.scala, client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/services/handlers/AllStaffAssignmentsHandler.scala, client/src/main/scala/drt/client/services/handlers/LegacyAllStaffAssignmentsHandler.scala
Make shift table loading more efficient
Rename some actions for consistency
=> DRTII-1561 Use indexes on assignment to improve filter performance

client/package-lock.json, client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/components/MonthlyShiftsUtil.scala, client/src/main/scala/drt/client/services/handlers/AllStaffAssignmentsHandler.scala, client/src/main/scala/drt/client/services/handlers/LegacyAllStaffAssignmentsHandler.scala, client/src/main/scala/drt/client/services/handlers/LegacyShiftsHandler.scala, client/src/main/scala/drt/client/services/handlers/StaffAssignmentsHandler.scala, client/src/test/scala/drt/client/components/MonthlyShiftsUtilSpec.scala, project/Settings.scala
- fixing update issue with latest changes
=> Drtii 1561 shift 3

client/package-lock.json, server/src/main/resources/routes, server/src/main/scala/controllers/application/SummariesController.scala, server/src/main/scala/services/liveviews/PassengersLiveView.scala, server/src/main/scala/uk/gov/homeoffice/drt/service/ApplicationService.scala, server/src/test/scala/controllers/application/SummariesControllerSpec.scala
Update pax population end point to:
- Also calculate & store capacities
- Take a date range for convenience
=> Drtii 1717 missing capacity in download manager for lhr

client/package-lock.json, client/src/main/scala/drt/client/SPAMain.scala, client/src/main/scala/drt/client/components/ArrivalsExportComponent.scala, client/src/main/scala/drt/client/components/DaySelectorComponent.scala, client/src/main/scala/drt/client/components/FlightTable.scala, client/src/main/scala/drt/client/components/FlightTableContent.scala, client/src/main/scala/drt/client/components/PaxCardComponent.scala, client/src/main/scala/drt/client/components/PaxSearchFormComponent.scala, client/src/main/scala/drt/client/components/PcpPaxSummariesComponent.scala, client/src/main/scala/drt/client/components/TerminalComponent.scala, client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/components/TerminalDashboardComponent.scala, client/src/main/scala/drt/client/components/TimeRangeFilter.scala, client/src/main/scala/drt/client/components/styles/LocalDateProvider.scala, client/src/main/scala/drt/client/services/SPACircuit.scala, client/src/test/scala/drt/client/components/FilterCrunchByRangeTests.scala, e2e/cypress/e2e/arrivals-page-filter.cy.ts, e2e/cypress/e2e/multi-day-export.cy.ts, e2e/cypress/e2e/staff-movements.cy.ts, e2e/cypress/e2e/view-modes.cy.ts, e2e/cypress/support/commands.ts, e2e/package-lock.json, e2e/package.json, project/Settings.scala, server/src/main/assets/stylesheets/main.less
- Replacing arrival page top section with react component which include day and time component and also pax number for next few minutes component 
- few of change in export buttons and reduced to menu
- few more style change mention in the ticket
=> Drtii 1674 arrival page top

client/package-lock.json, client/package.json, client/src/main/scala/drt/client/components/FlightTableRow.scala, client/vite.config.js, server/src/main/assets/stylesheets/main.less
DRTII-157 : changes for icon and removing padding from row
=> Drtii 1573 arrival table padding

client/package-lock.json, client/package.json, client/src/main/scala/drt/client/components/FeedsStatusPage.scala, client/src/main/scala/drt/client/components/FlightChartComponent.scala, client/src/main/scala/drt/client/components/FlightComponents.scala, client/src/main/scala/drt/client/components/FlightFlaggerFilters.scala, client/src/main/scala/drt/client/components/FlightTable.scala, client/src/main/scala/drt/client/components/FlightTableComponents.scala, client/src/main/scala/drt/client/components/FlightTableRow.scala, client/src/main/scala/drt/client/components/PassengerForecastAccuracyComponent.scala, client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/components/TerminalDesksAndQueues.scala, client/src/main/scala/drt/client/components/TerminalDesksAndQueuesRow.scala, client/src/main/scala/drt/client/components/TerminalPlanningComponent.scala, client/src/main/scala/drt/client/components/TippyJSComponent.scala, client/src/main/scala/drt/client/components/ToolTips.scala, client/src/main/scala/drt/client/modules/GoogleAnalytics.scala, server/src/main/resources/config/play.conf
Drtii 1742 adding analytics to planning page
Drtii 1743 adding analytics to tooltip and react component flight highlighter and first cell in flight row
=> Drtii 1743 adding analytics

server/src/main/scala/services/exports/StreamingDesksExport.scala, server/src/test/scala/services/exports/StreamingDesksExportSpec.scala
Grouping terminals for 15 minute interval
=> Drtii 1715 terminals

e2e/cypress/e2e/arrival-api-with-exports.cy.ts, e2e/cypress/e2e/arrival-sources.cy.ts, e2e/cypress/e2e/arrivals-flagger.cy.ts, e2e/cypress/e2e/arrivals-page-filter.cy.ts, e2e/cypress/e2e/arrivals-page.cy.ts, e2e/cypress/e2e/multi-day-export.cy.ts, e2e/cypress/e2e/port-dashboard.cy.ts, e2e/cypress/e2e/simulation-export.cy.ts, e2e/cypress/e2e/terminal-dashboard.cy.ts, e2e/cypress/e2e/view-modes.cy.ts, e2e/cypress/support/commands.ts, e2e/cypress/support/time-helpers.ts
Convert arrival scheduled time to utc before sending
=> DRTII-1779 Fix timezone issue in e2e terminal dash test

client/package.json
DRTII-1772 : Edit staff form midnight end error
=> Drtii 1772 edit staff

client/src/main/scala/drt/client/services/handlers/ShiftsHandler.scala, server/src/main/scala/controllers/application/ShiftsController.scala
DRTII-1842 : display staff assignment with shift creation
=> display staff assignment with shift creation

client/src/main/scala/drt/client/actions/Actions.scala, client/src/main/scala/drt/client/components/FeedsStatusPage.scala, client/src/main/scala/drt/client/services/handlers/AppControlHandler.scala, project/Settings.scala, server/src/main/resources/application-acp.conf, server/src/main/resources/application-inmemory.conf, server/src/main/resources/routes, server/src/main/scala/actors/CrunchManagerActor.scala, server/src/main/scala/actors/daily/TerminalDayFlightActor.scala, server/src/main/scala/actors/persistent/ManifestRouterActor.scala, server/src/main/scala/controllers/application/PortStateController.scala, server/src/main/scala/manifests/ManifestLookup.scala, server/src/main/scala/module/DrtModule.scala, server/src/main/scala/services/arrivals/RunnableGraphLike.scala, server/src/main/scala/services/arrivals/RunnableHistoricPax.scala, server/src/main/scala/services/arrivals/RunnableHistoricSplits.scala, server/src/main/scala/services/arrivals/RunnableLiveSplits.scala, server/src/main/scala/services/arrivals/RunnableUniqueArrivalsLike.scala, server/src/main/scala/services/crunch/CrunchManager.scala, server/src/main/scala/services/crunch/deskrecs/DynamicRunnablePassengerLoads.scala, server/src/main/scala/slickdb/AggregatedDbTables.scala, server/src/main/scala/uk/gov/homeoffice/drt/crunchsystem/ProdDrtSystem.scala, server/src/main/scala/uk/gov/homeoffice/drt/db/AggregateDb.scala, server/src/main/scala/uk/gov/homeoffice/drt/service/ApplicationService.scala, server/src/main/scala/uk/gov/homeoffice/drt/service/ManifestPersistence.scala, server/src/test/scala/services/crunch/TestDrtActor.scala
Update LGW splits via drt-lib
Add button to recalculate flight splits from live & historic api data
=> Drtii 1777 update lgw egate eligible pax percentages

client/src/main/scala/drt/client/components/FlightTableContent.scala, client/src/main/scala/drt/client/services/handlers/InitialPortStateHandler.scala, client/src/main/scala/drt/client/services/handlers/ViewModeHandler.scala
Display loading overlay when waiting for port state to load
=> DRTII-1851 Add overlay when port state is pending

client/package-lock.json, client/package.json, client/src/main/scala/drt/client/SPAMain.scala, client/src/main/scala/drt/client/components/QueueChartComponent.scala, client/src/main/scala/drt/client/components/TerminalContentComponent.scala, client/src/main/scala/drt/client/components/TerminalDesksAndQueues.scala, database_setup/aggregated-user.sql, server/src/main/assets/stylesheets/main.less, server/src/main/scala/controllers/Application.scala, server/src/main/scala/controllers/application/AuthController.scala, server/src/main/scala/slickdb/AggregatedDbTables.scala, server/src/main/scala/slickdb/UserTable.scala, server/src/main/scala/uk/gov/homeoffice/drt/testsystem/TestTables.scala, shared/src/main/scala/drt/shared/UserPreferences.scala
DRTII-1538: Reveal hourly breakdown on Desks and Queues
=> Drtii 1538 hourly breakdown

.drone-v1.yml, build.sbt, project/Settings.scala
DRTII-1893 - Update pax transaction times Q1 25-26
=> Drtii 1893 update pax transaction times q1 25 26

server/src/main/resources/config/feature-flags.conf, server/src/main/scala/actors/ProdDrtParameters.scala, server/src/main/scala/services/OptimiserWithFlexibleProcessors.scala, server/src/main/scala/services/crunch/deskrecs/TerminalDesksAndWaitsProvider.scala, server/src/main/scala/services/scenarios/Scenarios.scala, server/src/main/scala/uk/gov/homeoffice/drt/service/ApplicationService.scala, server/src/main/scala/uk/gov/homeoffice/drt/testsystem/TestTables.scala, server/src/test/scala/services/OptimiserSpec.scala, server/src/test/scala/services/OptimiserWithFlexibleProcessorsSpec.scala, server/src/test/scala/services/StaffDeploymentSpec.scala, server/src/test/scala/services/crunch/CrunchEgateBanksSpec.scala, server/src/test/scala/services/crunch/ForecastCrunchSpec.scala, server/src/test/scala/services/crunch/deskrecs/PortDesksAndWaitsProviderSpec.scala
Disable fair xmax by feature flag - causes under-deployments at BHX
=> Drtii 1927 min staff whenever pax join queue

client/src/main/scala/drt/client/components/PortDashboardPage.scala, client/src/main/scala/drt/client/services/handlers/UserPreferencesHandler.scala, project/Settings.scala
- adding none terminal when no terminals are selected as we want default all terminal to selected when user are viewing dashboard without any selection
=> Drtii 1890 dashboard error

project/Settings.scala, server/src/main/scala/controllers/application/ForecastAccuracyController.scala, server/src/main/scala/services/crunch/deskrecs/OptimisationProviders.scala, server/src/main/scala/services/prediction/ArrivalPredictions.scala, server/src/main/scala/uk/gov/homeoffice/drt/service/ApplicationService.scala
drt-lib update
Remove dead code
Only update cache for historic dates
Get flights from live view for updating capacities
=> DRTII-1949 drt-lib update

client/src/main/scala/drt/client/components/FlightChartComponent.scala, client/src/main/scala/drt/client/components/QueueChartComponent.scala
Convert old v2 option `xAxes` to v3 `x`
=> Drtii 1923 charts display issue

server/src/test/scala/services/PortStateSpec.scala, server/src/test/scala/services/crunch/PortStateSummariesSpec.scala, shared/src/main/scala/drt/shared/PortState.scala
Fix misc added to total deployed
=> Drtii 1969 fix desk and queues 1 hour view
