UKHomeOffice/drt-v2

- client/src/main/scala/spatutorial/client/SPAMain.scala
- client/src/main/scala/spatutorial/client/components/Heatmap.scala
- client/src/main/scala/spatutorial/client/components/MainMenu.scala
- client/src/main/scala/spatutorial/client/components/QueueUserDeskRecs.scala
- client/src/main/scala/spatutorial/client/components/TerminalDeployments.scala
- client/src/main/scala/spatutorial/client/services/SPACircuit.scala
- server/src/main/assets/stylesheets/main.less
- server/src/main/scala/actors/CrunchActor.scala
- server/src/test/scala/services/EGateBanksTests.scala
- server/src/test/scala/services/inputfeeds/StreamFlightCrunchTests.scala
- shared/src/main/scala/spatutorial/shared/HasAirportConfig.scala
Drive front end from airport config queue definitions rather than a hard coded list of queues
Style terminal page to account for 2, 3 & 4 queue terminals
> DRT-4453 Make queues configurable by terminal

- client/src/main/scala/spatutorial/client/services/StaffAssignmentParser.scala
- client/src/test/scala/spatutorial/client/services/SDateTests.scala
- Change JSSDate to always work in local time
- Using millisSinceEpoch will always return UTC time
> DRT-4583 Always use Localtime in JS

- server/src/main/scala/actors/CrunchStateActor.scala
- server/src/main/scala/services/Crunch.scala
- server/src/test/scala/services/StreamingSpec.scala
- Return only flights reaching PCP after the crunch start time
- Return workload for only the crunch period
- Return crunch results for only the crunch period
> DRT-4736 Fix crunch state actor responses

- client/src/main/scala/drt/client/components/FlightComponents.scala
- client/src/main/scala/drt/client/components/FlightsTable.scala
- client/src/main/scala/drt/client/components/FlightsWithSplitsTable.scala
- client/src/main/scala/drt/client/components/TerminalContentComponent.scala
- client/src/main/scala/drt/client/components/TerminalStaffing.scala
- client/src/test/scala/drt/client/components/FlightsTableTests.scala
- client/src/test/scala/drt/client/components/PaxSplitsDisplayTests.scala
This change fixes a bug where transfer pax were being subtracted twice
from the PCP pax when calculating queue totals.
> DRT-4845 Fix Queue ratio bug

- client/src/main/scala/drt/client/SPAMain.scala
- client/src/main/scala/drt/client/components/DateSelector.scala
- client/src/main/scala/drt/client/components/MultiDayExportComponent.scala
- client/src/main/scala/drt/client/components/TerminalContentComponent.scala
- server/src/main/assets/stylesheets/main.less
Adds a link to export multiple days for desks and queues.
- New link on current/snapshot pages to do the exports
- modal dialog to choose date range to export
- new date picker component
> DRT-4934 Multi-day export ui

- client/src/main/scala/drt/client/SPAMain.scala
- client/src/main/scala/drt/client/actions/Actions.scala
- client/src/main/scala/drt/client/services/SPACircuit.scala
- server/src/main/scala/controllers/Application.scala
- server/src/main/scala/services/ApiService.scala
- server/src/main/scala/services/shifts/StaffTimeSlots.scala
- server/src/test/scala/services/shifts/StaffTimeSlotsSpec.scala
- shared/src/main/scala/drt/shared/Api.scala
- Reduce shift names and remove whitespace from shift lines
- Convert first milli of month into europe/london timezone before removing existing shifts for the month
> DRT-4994 Fix monthly staffing

- project/Settings.scala
We were getting a stack trace:
> Caused by: java.lang.SecurityException: class "org.bouncycastle.math.ec.ECCurve$AbstractFp"'s signer information does not match signer information of other classes in the same package
We had thought it was due the Birmingham PR, but it was actually down to a library introduced by getting the Gatwick feed.
By excluding `org.bouncycastle` in the `opensaml` library we do not get the stack trace.
> DRT-4938 - removes the strange java security exception bug

- server/src/main/scala/drt/server/feeds/lgw/LGWFeed.scala
- server/src/test/scala/feeds/LGWFeedSpec.scala
a fix for Gatwick timeouts.
Currently Gatwick in DEV returns a 204 - no content and this seems to return a timeout that messes up `spray-client`. It retry's 5 times and the tick every 3 seconds ends.
This fix is still not ideal - but we still retry 5 times till it ends in the dead letter queue - but we do not kill the call to get the flights every 3 seconds and we do not flood the with network calls to get the flights when it retries.
> DRT-4938 - a fix for Gatwick timeouts

- server/src/main/scala/drt/server/feeds/lgw/LGWFeed.scala
Remove the throttle 
We are seeing that we are getting flights every 30 seconds.
Let's remove the throttle to see if they arrive more quicker
> Remove the throttle got Gatwick on the Source tick

- server/src/main/resources/application.conf
The idle-timeout is `The time after which an idle connection will be automatically closed.`
By default it is 60 seconds, but currently we have it set to 30 seconds.
We see the following in the logs;
``` 
Failed to fetch LGW arrivals. Re-requesting token. java.util.concurrent.TimeoutException: Futures timed out after [30 seconds]
```
I am unsure if this is related to the idle-timeout; but this is the only value that is 30 seconds. I have set it to 90 seconds so that it is an increase to the default value and if we still see 30 seconds in the logs we will know that there is another timeout we need to increase.
Let us see if by changing this value if we see more flight arrivals coming through in production.
If all else fails - we need to ask the Gatwick guys why we are missing flights. …
> Lets increase the idle timeout to 90 seconds.

- server/src/main/scala/drt/server/feeds/lgw/AzureSamlAssertion.scala
- server/src/main/scala/drt/server/feeds/lgw/LGWFeed.scala
- server/src/main/scala/drt/server/feeds/lgw/ResponseToArrivals.scala
- server/src/test/scala/feeds/LGWFeedSpec.scala
- Moved all the XML conversion to its own class and hardened it.
- Moved all the crazy opensaml stuff to it's own class.
- They return us not just 200 - but 201 and 204 status code. We need to cater for all these http status codes.
- They timeout in their url is regarding when they time us out to look for the head of arrivals in their message queue. I've shortened it to 25 seconds.
> Gatwick changes

- server/src/main/scala/drt/server/feeds/bhx/BHXArrivals.scala
- server/src/test/scala/feeds/BHXFeedSpec.scala
I feel very sorry for creating this PR. Feel free to not merge this, I think we should get Birmingham to fix their forecast times.
If we assume their giving us local times the scheduled time is behind by two hours.
The Flight Forecast app assumes it is UTC as we do - the trouble is that it's behind by one hour.
This PR is created to correct date times that seem to be one hour behind UTC for the forecast scheduled time. It would be better to call the people who create this feed and tell them to correct it.
> Birmingham Forecast Scheduled Time is off by one hour from UTC.

- client/src/main/scala/drt/client/components/TerminalDesksAndQueues.scala
Confirmation from LHR and STN that this calculation is preferred by comparing Rec with Available rather than Rec with Deployed
> Drt 4996 rag status against available

- server/src/main/scala/services/crunch/CrunchSystem.scala
- server/src/main/scala/services/graphstages/Crunch.scala
- server/src/main/scala/services/graphstages/StaffBatchUpdateGraphStage.scala
- server/src/main/scala/services/graphstages/StaffGraphStage.scala
- server/src/test/scala/services/crunch/StaffBatchUpdateGraphStageSpec.scala
Desk deployments for tomorrow are showing zero.
We were grouping the days to calculate the staff minutes without taking into account that different airport begin and end their day at different time periods.
> [DRT-5078] - Desk deployments for tomorrow are showing zero

- server/src/main/scala/services/graphstages/SimulationGraphStage.scala
- server/src/test/scala/services/crunch/StaffMinutesSpec.scala
Jira: https://jira.digital.homeoffice.gov.uk/browse/DRT-5099
When there are extra staff on duty in a time period, distribute them evenly amongst the queues.
> [DRT-5099] - Distributed desks evenly when more staff are available.

- server/src/main/scala/services/CSVData.scala
- server/src/test/scala/services/crunch/CrunchMinutesToCSVDataTest.scala
EMA desks and queues CSV - header `queueDesk` should be `Desk`.
> [NO_JIRA] - Found a bug when looking at EMA on pre-prod 

- server/src/main/resources/application.conf
Currently we get the following warning in the log files
2018-06-13 14:12:44,386 [main] WARN  application  - application.conf @ file:/usr/share/drt-v2/stn/drt-931/conf/application.conf: 7: parsers.text.maxLength is deprecated, use play.http.parser.maxMemoryBuffer instead
In the application.conf file we should use `play.http.parser.maxMemoryBuffer` instead of `parsers.text.maxLength`.
https://www.playframework.com/documentation/2.4.x/ScalaBodyParsers#Max-content-length
> [DRT-5129] - Max content length

- project/Settings.scala
- project/plugins.sbt
There is an `0.6.23` update to scala.js, we are currently using `0.6.19`.
https://www.scala-js.org/news/2018/05/22/announcing-scalajs-0.6.23/
Let us upgrade!
> [DRT-5132] - upgrade the scala.js plugin to 0.6.23

- client/src/main/scala/drt/client/components/TerminalDesksAndQueues.scala
Ema desk and queues page fix.
The forecast data was in preprod before we renamed the queue from eeaDesk to desks.
This fix will filter out the data that's not required before we show the page.
> DRT-5128 - Ema desk and queues page fix

- build.sbt
- project/Settings.scala
- project/plugins.sbt
Play 2.6.15 is released.
https://blog.playframework.com/play-2-6-15-released/
Let's upgrade!
I followed the migration steps - by adding some extra play dependencies.
One test failed -> drt.chroma.DiffingAkkaStreamSpec
I upgraded akka libraries and all the test passed.
> [DRT-5134] - Playframework upgrade to 2.6.15

- project/Settings.scala
The Renjin code that gets executed is probably the slowest and most unknown part of the app.
Unfortunately, it's not clear what has changed from the previous version  `0.8.2195`, but there have been lots of subsequent changes going by the version numbers. 
http://docs.renjin.org/en/latest/library/project-setup.html#scala-build-tool-sbt
> [DRT-5136] - upgrade renjin to `0.9.2646`.

- client/src/main/scala/drt/client/services/JSDateConversions.scala
- project/Settings.scala
Introduce moment.js to get consistent times across the app.
The scala.js facade for moment.js [here](https://github.com/vpavkin/scala-js-momentjs) was used.
> [DRT-5147] - consistent times across the app

- server/src/main/scala/controllers/Application.scala
- server/src/main/scala/drt/server/feeds/acl/AclFeed.scala
- server/src/test/scala/services/inputfeeds/AclFeedSpec.scala
We see lots of errors in the logs
```
2018-07-11 02:34:17,329 [reader] ERROR n.s.sshj.transport.TransportImpl  - Dying because - Connection reset
2018-07-11 02:34:18,305 [reader] ERROR n.s.sshj.transport.TransportImpl  - Dying because - Connection reset
2018-07-11 03:34:17,372 [reader] ERROR n.s.sshj.transport.TransportImpl  - Dying because - Connection reset
```
They occur every hour which corresponds to when we get ACL data.
After doing a quick google search I saw this [post](https://github.com/hierynomus/sshj/issues/87):
It is my best guess that if we close the ssh connection it is possible that we will not see these error message in the logs.
> DRT-5159 - Remove errors in logs: `Dying because Connection reset`

- server/src/main/scala/drt/server/feeds/ltn/LtnLiveFeed.scala
LTN port feed failed and needed a restart of the app to get it going again.
Here are the logs from the event.
```
2018-07-10 05:42:48,000 [application-akka.actor.default-dispatcher-88] INFO c.g.ArrivalsGraphStage$$anon$1- - inFlightsLive.in(2102223838) Took 86ms
2018-07-10 05:43:06,086 [application-akka.actor.default-dispatcher-76] INFO s.g.VoyageManifestsGraphStage - Fetched 0 manifests up to file drt_dq_180710_063210_9458.zip
2018-07-10 05:43:06,086 [application-akka.actor.default-dispatcher-76] INFO s.g.VoyageManifestsGraphStage - Pushing 0 new manifests
2018-07-10 05:43:06,086 [application-akka.actor.default-dispatcher-76] INFO s.g.VoyageManifestsGraphStage - Minimum check interval 60000ms not yet reached. Sleeping for 20167ms
2018-07-10 05:43:06,086 …
```
> DRT-5163 - LTN Port feed failure

- server/src/main/scala/controllers/Application.scala
- server/src/test/resources/application.conf
- server/src/test/scala/controllers/ApplicationSpec.scala
The Export Desks CSV which misses the last time in a given date/time range.
e.g. a CVS file generated from 13:00 to 17:00 will omit the last time at 17:00
The CSV will now include the last time from a given date range.
> DRT-5166 - Export Desks CSV should include the last date time in the range

- server/src/main/scala/drt/server/feeds/lgw/ResponseToArrivals.scala
- server/src/test/scala/feeds/LGWFeedSpec.scala
Currently the LGW feed status has codes such as `LAN`, `FRB` and `LSB` that does not make sense to an English speaking person.
We should show the description of the status codes instead.
The table below are the current, _valid_ status codes they use and what they mean.
AIDX Code | AIDX Code Context | IDAHO Code | Description
-- | -- | -- | --
FCT | 9750 | LC | Last Call (Departure Only)
BST | 9750 | BD | Boarding   (Departure Only)
DV | 2005 | DV | Diverted   (Arrival Only)
DX | 2005 | CX | Cancelled
EST | 2005 | ES | Estimated
EXP | 0000 | EX | Expected
FRB | 0000 | FB | First   Bag Delivered (Arrival Only)
GCL | 9750 | GC | Gate   Closed (Departure Only)
GOP | 0000 | GO | Gate   Opened (Departure Only)
LAN | 9750 | LD | Landed   (Arrival Only)
LSB | 0000 | LB | Last   Bag Delivered …
> DRT-5165 - Improve LGW's live feed statuses

- client/src/main/scala/drt/client/SPAMain.scala
- client/src/main/scala/drt/client/actions/Actions.scala
- client/src/main/scala/drt/client/components/ListKeyCloakUsers.scala
- client/src/main/scala/drt/client/components/MainMenu.scala
- client/src/main/scala/drt/client/components/Navbar.scala
- client/src/main/scala/drt/client/components/SnapshotSelector.scala
- client/src/main/scala/drt/client/services/SPACircuit.scala
- client/src/main/scala/drt/client/services/handlers/UsersHandler.scala
- server/src/main/assets/stylesheets/main.less
- server/src/main/resources/application.conf
- server/src/main/scala/controllers/Application.scala
- server/src/main/scala/drt/http/SendAndReceive.scala
- server/src/main/scala/drt/users/KeyCloakClient.scala
- server/src/main/scala/services/ApiService.scala
- server/src/main/scala/test/MockRoles.scala
- server/src/main/scala/test/TestDrtSystem.scala
- server/src/test/scala/drt/users/KeyCloakApiSpec.scala
- shared/src/main/scala/drt/shared/Api.scala
- shared/src/main/scala/drt/shared/KeyCloakApi.scala
- Connect to Keycloak API to get all users for realm
- Display users who are not in "Approved" key cloak group
- add "Approve" action to add key cloak users to the Approved group
- Only allow users with "manage-users" role to approve user
> DRT-5096 Allow Key Cloak User Approval from app

- server/src/main/scala/actors/DrtSystem.scala
- server/src/main/scala/actors/VoyageManifestsActor.scala
- server/src/main/scala/drt/server/feeds/api/S3ApiProvider.scala
- server/src/main/scala/services/graphstages/ArrivalsGraphStage.scala
- server/src/main/scala/services/graphstages/VoyageManifestsGraphStage.scala
- server/src/test/scala/services/crunch/ApplicationRestartSpec.scala
- server/src/test/scala/services/crunch/ForecastCrunchSpec.scala
- server/src/test/scala/services/crunch/VoyageManifestsGraphStageSpec.scala
- server/src/test/scala/services/crunch/WorkloadGraphStageSpec.scala
- Factor out the API data provider from the manifest stage to make the stage testable
- Add missing failure case for manifest parser
- Unrelated... only purge expired arrivals when they're merged rather than beforehand too - reduces server load on startup
> Drt 5178 improve api feed test coverage

- server/src/main/resources/application.conf
- server/src/main/scala/Filters.scala
- server/src/main/scala/controllers/Application.scala
- server/src/main/scala/controllers/Test.scala
Whilst reading [this](https://www.playframework.com/documentation/2.6.x/ScalaAkka#Creating-and-using-actors) when investigating #DRT-5174 - running akka in a cluster; 
It was noted that some of our Controllers are not Singletons
Play Controllers must be a singleton or else it would need to create actors with a unique names.
> if the controller was not scoped as singleton, this would mean a new actor would be created every time the controller was created, which would ultimate throw an exception because you can’t have two actors in the same system with the same name.
> DRT-5177- Play Controllers with akka

- client/src/main/scala/drt/client/services/handlers/CrunchUpdatesHandler.scala
In production we see this JS error
``` javascript
client-opt-library.js?1027:506 Failed to GetCrunchState. Re-requesting after 2 seconds
```
This PR removes it by logging the output at info rather than at error level.
> DRT-5192 - Remove the GetCrunchUpdates JS error

- server/src/main/scala/actors/DrtSystem.scala
- server/src/main/scala/services/crunch/CrunchSystem.scala
- server/src/main/scala/services/graphstages/ArrivalSplitsGraphStage.scala
- server/src/main/scala/services/graphstages/ArrivalsGraphStage.scala
- server/src/test/scala/services/crunch/ArrivalSplitsStageSpec.scala
- server/src/test/scala/services/crunch/CrunchTestLike.scala
- server/src/test/scala/services/crunch/VoyageManifestsSpec.scala
To counter the API splits going missing some time after an app restart this PR enables the initialisation of the ArrivalSplitsGraphStage with the currently known manifests so that any flights which lose them can have them added again.
It also stops manifests being removed from the stage's manifest buffer when they're matched to flights as an extra guard. Ie the stage will still have the API splits available to add to a flight if that flight's splits go missing
> Drt 5149 initialise manifests buffer in splits stage

- server/src/main/scala/drt/chroma/ArrivalsDiffingStage.scala
- server/src/test/scala/drt/chroma/DiffingAkkaStreamSpec.scala
- server/src/test/scala/services/crunch/ArrivalsGraphStageSpec.scala
Fights will be moved after chox this data will skew our PCP arrival times. Only subsequent updates that include a change to chox time should be considered.
Given a flight with no chox time
When an update to the flight comes through in the feed
Then that change should be reflected on the dashboard
Given a flight which already has a chox time
When an update to the flight comes through the feed that contains the same chox time
Then that change should NOT be reflected in the dashboard
Given a flight which already has a chox time
When an update to the flight comes through the feed that contains a different chox time
Then that change should be reflected along with all other changes in that update
> DRT-4661 - Don't adjust flight after chox

- shared/src/main/scala/drt/shared/HasAirportConfig.scala
Ltn eea and Non-eea desks as they were before
EGate desks max set to 2 for each hour.
> DRT-5168 - Ltn eea and Non-eea desks as they were before

- e2e/cypress/integration/monthly-staffing.js
- e2e/cypress/integration/staff-movements.js
I don't see what changes now makes all these tests pass on dev.
This makes no sense, however, we will try and switch on the failing tests and see if they pass on jenkins.
Ever since the PR was merged today to add id attributes to some Html elements the tests seem to pass.
They pass locally against the dev environment.
> DRT-5182 - Turn on all the tests, they seem to work.

- e2e/cypress/integration/monthly-staffing.js
- e2e/package-lock.json
- e2e/package.json
This fixes the current failing e2e tests called `monthly staffing`.
Included the `moment-timezone` library to set the timezone to `Europe/London`.
This fixes the test by correcting the setup of the data to set the staff at 12am rather than 1am for the first day of this month and next month.
The test will then continue to verify the data for this month and next month have the expected values setup on the first day of the month at 12am using the monthly staffing UI.
> DRT-5182 - Resolve Failing E2E Tests

- server/src/main/scala/actors/StaffMovementsActorBase.scala
The created by is now persisted. It needed to be serialised into a protobuf message.
The image below show the email address finally being persisted on a staff movement after restarting the application.
> DRT-5250 - Staff Movement `Created by` is persisted after a restart

- client/src/main/scala/drt/client/actions/Actions.scala
- client/src/main/scala/drt/client/components/FlightsWithSplitsTable.scala
- client/src/main/scala/drt/client/components/TerminalComponent.scala
- client/src/main/scala/drt/client/components/TerminalContentComponent.scala
- client/src/main/scala/drt/client/services/handlers/CrunchUpdatesHandler.scala
- client/src/main/scala/drt/client/services/handlers/LoaderHandler.scala
- server/src/main/scala/controllers/Application.scala
- server/src/main/scala/services/ApiService.scala
- shared/src/main/scala/drt/shared/Api.scala
Shows `"No flights to display"` when there are no arrivals in the time period selected but there are crunch state on the selected day on the `Arrivals` tab.
Shows a spinner when it's requesting crunch for a time period. i.e. It does not show the `Desks & Queues`, `Arrivals` and `Staff Movements` tab.
Shows `"Nothing to show for this time period"` when there are no crunch state for the selected time period. i.e. It does not show the `Desks & Queues`, `Arrivals` and `Staff Movements` tab.
Will show the `Desks & Queues`, `Arrivals` and `Staff Movements` tab when the crunch data arrives.
> Drt 5075 - Loading flights message

- client/src/main/scala/drt/client/SPAMain.scala
- client/src/main/scala/drt/client/actions/Actions.scala
- client/src/main/scala/drt/client/components/FlightsWithSplitsTable.scala
- client/src/main/scala/drt/client/components/TerminalComponent.scala
- client/src/main/scala/drt/client/components/TerminalContentComponent.scala
- client/src/main/scala/drt/client/components/TerminalsDashboardPage.scala
- client/src/main/scala/drt/client/modules/GoogleAnalytics.scala
- client/src/main/scala/drt/client/services/handlers/CrunchUpdatesHandler.scala
- client/src/main/scala/drt/client/services/handlers/LoaderHandler.scala
- client/src/main/scala/drt/client/services/handlers/ViewModeHandler.scala
- e2e/cypress.json
- e2e/cypress/integration/alerts.js
- e2e/cypress/integration/arrival.js
- e2e/cypress/integration/staff-movements.js
- e2e/package-lock.json
- e2e/package.json
- server/src/main/scala/controllers/Application.scala
- server/src/main/scala/services/ApiService.scala
- server/src/main/twirl/views/index.scala.html
- shared/src/main/scala/drt/shared/Api.scala
This is the puts back the PR [#552 Loading flights message](https://github.com/UKHomeOffice/drt-v2/pull/552)
> - Shows "No flights to display" when there are no arrivals in the time period selected but there are crunch state on the selected day on the Arrivals tab.
> - Shows a spinner when it's requesting crunch for a time period. i.e. It does not show the Desks & Queues, Arrivals and Staff Movements tab.
> - Shows "Nothing to show for this time period" when there are no crunch state for the selected time period. i.e. It does not show the Desks & Queues, Arrivals and Staff Movements tab.
> - Will show the Desks & Queues, Arrivals and Staff Movements tab when the crunch data arrives.
The PR was fine when running locally, however not when running it in production mode. There was a …
> Revert 560 fixing e2e tests

- client/src/main/scala/drt/client/components/AlertsPage.scala
- client/src/main/scala/drt/client/components/DatePickerComponent.scala
- client/src/main/scala/drt/client/components/ListKeyCloakUsers.scala
- client/src/main/scala/drt/client/components/MultiDayExportComponent.scala
- client/src/main/scala/drt/client/components/Navbar.scala
- client/src/main/scala/drt/client/components/SnapshotSelector.scala
- client/src/main/scala/drt/client/components/StaffDeploymentsAdjustmentPopover.scala
- client/src/main/scala/drt/client/components/StatusPage.scala
- client/src/main/scala/drt/client/components/TerminalComponent.scala
- client/src/main/scala/drt/client/components/TerminalContentComponent.scala
- client/src/main/scala/drt/client/components/TerminalDesksAndQueues.scala
- client/src/main/scala/drt/client/components/TerminalPlanningComponent.scala
- client/src/main/scala/drt/client/components/TerminalStaffing.scala
- client/src/main/scala/drt/client/components/TerminalStaffingV2.scala
- client/src/main/scala/drt/client/components/TerminalsDashboardPage.scala
- client/src/main/scala/drt/client/components/TimeRangeFilter.scala
- client/src/main/scala/drt/client/components/VersionUpdateNotice.scala
- client/src/main/scala/drt/client/modules/GoogleAnalytics.scala
- client/src/main/scala/drt/client/services/ErrorHandler.scala
- server/src/main/resources/application.conf
- server/src/main/scala/controllers/Application.scala
- server/src/main/twirl/views/index.scala.html
- Given access to google analytics to drtdevteam@digital.homeoffice.gov.uk
- Any new members will need to have a google account for their existing email (https://support.google.com/accounts/answer/176347)
- Got two trackers for DRT-Prod and DRT-NotProd
- Creates a tracker with an associated `userId`, so a view (User Enabled View) _can_ _report_ on User Activity
- Added events and pageViews on the app
- Prefixes pageViews and events with the current port to enable Reporting per port.
> DRT-5260 - Add Google Analytics Data

- server/src/test/scala/services/CodeSharesSpec.scala
- shared/src/main/scala/drt/shared/CodeShares.scala
Revert codeshare matching criteria and keep the flags used for the different feeds
> DRT-5148 - Revert codeshare matching criteria

- server/src/main/resources/application.conf
- server/src/main/scala/actors/DrtSystem.scala
- server/src/main/scala/drt/server/feeds/api/S3ApiProvider.scala
Rather than a profile name which relies on a credentials file existing on the server
> DRT-5229 Populate aws credentials from environment vars

- server/src/main/scala/drt/server/feeds/acl/AclFeed.scala
Whilst looking at high memory usage on LHR with Rich, I noticed we may not be closing sftp connections on failure/timeout.
> DRT-5290 - Close sftp connection

- server/src/main/scala/drt/server/feeds/acl/AclFeed.scala
This is to correct the last PR.
Obviously we don't want to close the sftp connection before we fetch the data.
> DRT-5290 - Close sftp connection - correction

- client/src/main/scala/drt/client/components/AlertsComponent.scala
- client/src/main/scala/drt/client/components/Layout.scala
- client/src/main/scala/drt/client/components/MainMenu.scala
- client/src/main/scala/drt/client/components/TerminalsDashboardPage.scala
- server/src/main/assets/stylesheets/main.less
- server/src/test/scala/services/crunch/CrunchTestLike.scala
- shared/src/main/scala/drt/shared/LoggedInUser.scala
Moved the Alert message to be inline with the logo.
Added a `create-alerts` role, for users who can create alerts.
Edit:
I've had to escape the calc css in less as it does not calculate the value correctly otherwise.
It's 100% minus the logo width in px. Consequently I could not find a way of putting this width as a variable as it's escaped in quotes.
> DRT-5283 - Move alert message to be inline with the logo

- client/src/main/scala/drt/client/modules/GoogleAnalytics.scala
# Google Analytics anonymizeIp
When you annoimise the IP it impacts the geolocation tracking data at city level (not at continent/country level).
To test on the network tab in your browser the url to google should have `aip=1` as a parameter
e.g.
> DRT-5260 - Google Analytics anonymizeIp

- shared/src/main/scala/drt/shared/StaffAssignment.scala
We had an inefficient call to millisSinceEpoch on an sdate inside a very big loop
It's possibly more inefficient since we started using Moment dates in the client SDate
> Drt 5313 monthly staffing very slow

- client/src/main/scala/drt/client/actions/Actions.scala
- client/src/main/scala/drt/client/components/StaffDeploymentsAdjustmentPopover.scala
- client/src/main/scala/drt/client/components/TerminalStaffing.scala
- client/src/main/scala/drt/client/services/handlers/StaffMovementsHandler.scala
- server/src/main/protobuf/StaffMovementMessages.proto
- server/src/main/scala/actors/StaffMovementsActorBase.scala
- server/src/main/scala/actors/pointInTime/StaffMovementsReadActor.scala
- server/src/main/scala/controllers/StaffMovementsPersistence.scala
- server/src/test/resources/application.conf
- server/src/test/scala/actors/AkkaTestkitSpecs2SupportForPersistence.scala
- server/src/test/scala/actors/StaffMovementsActorSpec.scala
- shared/src/main/scala/drt/shared/Api.scala
Send additions & removals to the backend when movements are added and removed rather than all of the known movements
Start persisting additions and removals rather than exclusively snapshotting
> Drt 5319 improve handling of adding and removing movements

- server/src/main/assets/stylesheets/main.less
Have the image show up so that css doesn't point to a path of an image that will not exist in ACP, or in UKCloud if the port Stansted goes down.
Used a relative path. Relative to the stylesheet path rather than the URL. This is probably not ideal, but better than an alternative I can think of.
The image show up:
> DRT-5205 - put missing image back using a relative path in the css

- build.sbt
- server/src/main/resources/application.conf
- server/src/main/resources/postgres.conf
- server/src/main/scala/Filters.scala
- server/src/main/scala/controllers/Application.scala
- server/src/main/scala/filters/ACPRedirectFilter.scala
- server/src/main/scala/filters/NoCacheFilter.scala
- server/src/main/scala/filters/SecurityHeadersFilter.scala
- server/src/test/scala/filters/ACPRedirectFilterSpec.scala
Redirects to ACP version of the port when a feature switch is set.
Moved application filters to a filters package.
Added play's specs2 dependency to unit test for the new filter
By default, the feature flag is set to false, i.e will not redirect to the ACP version of the port.
Assumed the ACP version of the port is;
```
https://<portcode>.drt.homeoffice.gov.uk/v2/<portcode>/live
```
> DRT-5349 - Redirect to ACP version of the port when the feature switch is set

- e2e/cypress/integration/alerts.js
- e2e/cypress/integration/api-splits-for-port-operators.js
- e2e/cypress/integration/arrival.js
- e2e/cypress/integration/monthly-staffing.js
- e2e/cypress/integration/restrict-access-by-port.js
- e2e/cypress/integration/staff-movements.js
- e2e/cypress/support/commands.js
- server/src/main/resources/routes
- server/src/main/scala/controllers/Application.scala
- shared/src/main/scala/drt/shared/LoggedInUser.scala
Initially we can reproduce the CSV export as an API endpoint 
This will require:
- restricting access to only the endpoint that it requires
- E2E tests to ensure this role doesn't accidentally gain access to things it shouldn't
> DRT-5348 - Create API to expose Adv Pax Info Splits to port operators

- server/src/main/scala/actors/AggregatedArrivalsActor.scala
- server/src/main/scala/actors/ArrivalsActor.scala
- server/src/main/scala/actors/CrunchStateActor.scala
- server/src/test/scala/services/crunch/ArrivalUpdatesCorrectlyAffectLoads.scala
- shared/src/main/scala/drt/shared/Api.scala
Remove pcp time field to prevent multiple keys being stored for the same arrival
> DRT 5833 Fix uniqueness of arrival keys

- server/src/main/scala/controllers/Application.scala
- server/src/main/scala/services/CSVData.scala
- server/src/test/scala/services/crunch/CrunchMinutesToCSVDataTest.scala
- server/src/test/scala/services/export/DesksAndQueuesExportSpec.scala
- shared/src/main/scala/drt/shared/Summaries.scala
Reworking of the export. No longer assumes data exists for every minute. Empty data is now filled in with appropriate zeros or empty cells.
Days are processed sequentially in a stream rather than waiting for all data before processing. This reduces the memory footprint
Also addresses DRT-5862 - streaming data to the browser
> Drt 5864 missing data in multi day export

- client/src/main/scala/drt/client/components/MainMenu.scala
- client/src/main/scala/drt/client/components/TerminalComponent.scala
- client/src/main/scala/drt/client/components/TerminalDashboardComponent.scala
- only count passengers for the terminal in to total PCP pax block
- don't retain timeslot when switching terminals
> DRT-5774 fix bugs in Terminal Dashboard page

- client/src/main/scala/drt/client/components/PortDashboardPage.scala
- client/src/main/scala/drt/client/components/TerminalContentComponent.scala
- client/src/main/scala/drt/client/components/TerminalDashboardComponent.scala
- server/src/test/scala/services/AirportConfigSpec.scala
- shared/src/main/scala/drt/shared/HasAirportConfig.scala
Use terminal split queue types to determine pax splits to display in arrivals table
> DRT-6002 Fix arrivals table splits display

- server/src/main/scala/actors/DrtSystem.scala
- server/src/main/scala/services/graphstages/Crunch.scala
- server/src/test/scala/manifests/graph/ManifestGraphSpec.scala
- server/src/test/scala/services/PortStateSpec.scala
- server/src/test/scala/services/crunch/AggregatedArrivalsSpec.scala
- server/src/test/scala/services/crunch/ApiPaxNosCrunchSpecSpec.scala
- server/src/test/scala/services/crunch/ApplicationRestartSpec.scala
- server/src/test/scala/services/crunch/ArrivalUpdatesCorrectlyAffectLoads.scala
- server/src/test/scala/services/crunch/ArrivalsGraphStageSpec.scala
- server/src/test/scala/services/crunch/BlackJackFlowSpec.scala
- server/src/test/scala/services/crunch/CodeshareWorkloadSpec.scala
- server/src/test/scala/services/crunch/CrunchCodeSharesSpec.scala
- server/src/test/scala/services/crunch/CrunchEgateBanksSpec.scala
- server/src/test/scala/services/crunch/CrunchFlightExclusionsSpec.scala
- server/src/test/scala/services/crunch/CrunchQueueAndTerminalValidationSpec.scala
- server/src/test/scala/services/crunch/CrunchSplitsToLoadAndDeskRecsSpec.scala
- server/src/test/scala/services/crunch/CrunchTestLike.scala
- server/src/test/scala/services/crunch/CrunchTimezoneSpec.scala
- server/src/test/scala/services/crunch/FlightUpdatesTriggerNewPortStateSpec.scala
- server/src/test/scala/services/crunch/ForecastCrunchSpec.scala
- server/src/test/scala/services/crunch/LiveStateRollingForwardSpec.scala
- server/src/test/scala/services/crunch/PlanningActualStaffSpec.scala
- server/src/test/scala/services/crunch/PlanningPageSpec.scala
- server/src/test/scala/services/crunch/StaffMinutesSpec.scala
- server/src/test/scala/services/crunch/VoyageManifestsSpec.scala
- server/src/test/scala/services/crunch/deskrecs/RunnableDeskRecsSpec.scala
- server/src/test/scala/services/inputfeeds/AclFeedSpec.scala
Trigger `manifest refresh flag` when the `refresh arrivals flag` is set to ensure manifests are looked up for the new arrivals
> Drtii 5 missing historic manifests for long range forecast

- server/src/main/scala/services/exports/Exports.scala
- server/src/test/scala/services/export/DesksAndQueuesExportSpec.scala
A fix to ensure export csv headers are present in the absence of data
> Drtii 348 headers for empty exports

- server/src/main/scala/services/crunch/deskrecs/DesksAndWaitsTerminalProvider.scala
- server/src/main/scala/services/crunch/deskrecs/RunnableDeskRecs.scala
- server/src/test/scala/services/StreamingWorkloadSpec.scala
- server/src/test/scala/services/crunch/CrunchSplitsToLoadAndDeskRecsSpec.scala
- server/src/test/scala/services/crunch/FlightUpdatesTriggerNewPortStateSpec.scala
- server/src/test/scala/services/crunch/deskrecs/RunnableDeskRecsSpec.scala
This fixes the case where a terminal with no flights doesn't get crunched resulting in phantom pax & wait times
> DRTII-355 Crunch all terminals rather than just the ones with flights

- server/src/main/scala/actors/DrtSystem.scala
- server/src/main/scala/services/crunch/CrunchSystem.scala
- server/src/main/scala/services/graphstages/DeploymentGraphStage.scala
- server/src/main/scala/services/graphstages/LegacyDeploymentGraphStage.scala
- server/src/main/scala/test/TestDrtSystem.scala
- server/src/test/scala/services/crunch/CrunchTestLike.scala
- server/src/test/scala/services/crunch/ReCrunchSpec.scala
Refactor to
- Start runnable desk recs after the runnable crunch so we are ready to receive simulation requests
- Reset terminals with zero staff to zero deployments and zero wait times
> DRTII-375 

- server/src/main/scala/actors/DrtSystemInterface.scala
- server/src/main/scala/actors/MinutesActor.scala
- server/src/main/scala/controllers/application/WithFeeds.scala
- server/src/main/scala/manifests/ManifestLookup.scala
- server/src/main/scala/manifests/graph/ManifestsGraph.scala
- server/src/test/scala/manifests/graph/ManifestGraphSpec.scala
To reduce strain on resources like database connections, cpu & memory, we should use a controlled sequence of asynchronous operations. `Future.sequence` executes all the futures in parallel and can result in large amounts of resources being used. `mapAsync` makes sure the futures are executed at most by `parallelism` at a time
> Drtii 403 future sequence to source map async

- server/src/main/scala/actors/DrtSystemInterface.scala
- server/src/main/scala/drt/server/feeds/lhr/LHRForecastFeed.scala
- server/src/test/scala/drt/server/feeds/lhr/LHRForecastFeedSpec.scala
Use `mapAsync` to eliminate need for `Await.result`
Add test
> Drtii 444 unhandled lhr forecast feed exception

- server/src/main/scala/actors/PortStateActor.scala
- server/src/main/scala/services/crunch/deskrecs/DesksAndWaitsPortProvider.scala
- server/src/main/scala/test/TestActors.scala
- server/src/test/scala/actors/CrunchStateMockActor.scala
- server/src/test/scala/actors/PortStateTestActor.scala
- server/src/test/scala/services/PortStateSpec.scala
- server/src/test/scala/services/crunch/StaffMinutesSpec.scala
- server/src/test/scala/services/crunch/TestDrtActor.scala
Fix case where a request for state is processed before the PortStateActor has received its state from the crunch state actors
PortStateActor now stashes messages until it's received its initial state, and then `becomes` the regular behaviour to begin processing messages requested
Tests now pass initial state to the crunch state actors rather than sending a message to the port state actor. Code to set state via a message has been removed as it was only used in tests
> Drtii 503 wait for state initialisation before processing messages

- server/src/main/scala/actors/FlightsStateActor.scala
- server/src/main/scala/actors/MinuteLookups.scala
- server/src/main/scala/actors/PartitionedPortStateActor.scala
- server/src/main/scala/actors/PortStateActor.scala
- server/src/main/scala/actors/ProdDrtSystem.scala
- server/src/main/scala/actors/pointInTime/CrunchStateReadActor.scala
- server/src/main/scala/actors/pointInTime/FlightsStateReadActor.scala
- server/src/main/scala/test/TestActors.scala
- server/src/main/scala/test/TestMinuteLookups.scala
- server/src/test/scala/actors/FlightsStateActorResponsesSpec.scala
- server/src/test/scala/actors/PartitionedPortStateActorSpec.scala
- server/src/test/scala/actors/PartitionedPortStateTestActor.scala
- server/src/test/scala/actors/PortStateTestActor.scala
- server/src/test/scala/services/PortStateSpec.scala
- server/src/test/scala/services/crunch/PortStateRequestsSpec.scala
- shared/src/main/scala/drt/shared/airportconfig/Lhr.scala
Use the snapshotInterval from AirportConfig for replaying CrunchState messages, allowing us to override the default value of 1000
> Drtii 544 replay more crunch state messages at ema

- server/src/main/scala/actors/queues/QueueLikeActor.scala
- server/src/test/scala/actors/queues/CrunchQueueSpec.scala
- server/src/test/scala/actors/queues/DeploymentQueueSpec.scala
- server/src/test/scala/manifests/graph/ManifestGraphSpec.scala
Stop sending Acks as they're being logged as errors now
Fix tests - unfortunately this means waiting a short time to be sure things are persisted before terminating
Possibly fix for the flaky manifests test
> Drtii 564 stop acking updatedmillis

- server/src/main/scala/actors/FlightsStateActor.scala
- server/src/test/scala/actors/FlightsStateActorSpec.scala
- Add test to guard against historic queries not getting looked at first
> DRTII-577 Fix for historic end-of-day flight queries

- server/src/main/scala/actors/ArrivalsActor.scala
- server/src/main/scala/actors/daily/UpdatesSupervisor.scala
- Only update the last request-time on a successful response
- A run of unsuccessful responses will result in the actor being shut down and removed due to an old last-request time
- Remove unused actors from the two maps before shutting them down to reduce the chances of them being queried as they're shut down
> Drtii 574 properly handle dead streaming updates actors

- server/src/main/scala/services/PaxDeltas.scala
- server/src/test/scala/services/PaxDeltasSpec.scala
- Improve tests to explicitly use UTC and hardcoded dates rather than relying on a function to calculate them
- Use `getUtcLastMidnight` rather than `getLocalLastMidnight` to correctly find pax nos stored against UTC dates
> DRTII-589 Use UTC tz for pax count days. Update tests

- .drone.yml
- client/src/main/scala/drt/client/components/Layout.scala
- client/src/main/scala/drt/client/components/RestrictedAccessByPortPage.scala
- e2e/tests/integration/api-role-access.ts
- e2e/tests/integration/errors.ts
- e2e/tests/integration/restrict-access-by-port.ts
- e2e/tests/support/commands.ts
- project/Settings.scala
- server/src/main/resources/config/common.conf
- server/src/main/scala/controllers/Application.scala
- server/src/main/scala/controllers/application/WithAuth.scala
- server/src/test/resources/application.conf
- shared/src/main/scala/drt/shared/airportconfig/Test.scala
- shared/src/main/scala/drt/shared/airportconfig/Test2.scala
Add the drt domain to configuration
Add `test` port access to some of the e2e tests that didn't already have it to prevent redirection to the registration app]
Redirect to the central app where a user does not have access to the port in question
> Drtii 627 redirect new users to access request form

- client/src/main/scala/drt/client/components/FlightComponents.scala
- server/src/test/scala/drt/shared/ApiFlightWithSplitsSpecs.scala
- shared/src/main/scala/drt/shared/Api.scala
Take pax count direct from the splits rather than the arrival
> Drtii 810 disappearing api pax nos from pax popup

- client/src/main/scala/drt/client/components/FlightComponents.scala
- client/src/test/scala/drt/client/components/PaxSplitsDisplayTests.scala
- server/src/test/scala/drt/shared/ApiFlightWithSplitsSpec.scala
- shared/src/main/scala/drt/shared/Api.scala
- shared/src/main/scala/drt/shared/splits/ApiSplitsToSplitRatio.scala
- we appear to lose the event code for live api when persisted. not an issue at the mo as we only use DC
- dont serve up historic api pax nos when asking for live api pax nos
- tests around these two fixes
> DRTII-844 Fix not picking up persisted API

- client/src/main/scala/drt/client/components/FlightsWithSplitsTable.scala
- server/src/test/scala/drt/shared/redlist/RedListSpec.scala
- shared/src/main/scala/drt/shared/redlist/RedList.scala
Implement red list change sets
Add historic change sets so we have the actual red list for a given point in time
Only use `LHRDirectRedListFlights` if the flight in question is scheduled since red list terminals opened
> Drtii 871 lhr shows outgoing redirected pax for pre red list dates

- e2e/tests/integration/multi-day-export.ts
- min desks at 4am in BST will be 1
- min desks at 3am in GMT will also be 1
> DRTII-926 Change UTC landing time to 3am

- project/Settings.scala
- Just update version of DRT lib . INV was there in version 12 but somehow missed in version 13 , maybe due to merge conflict .
> DRT-533 update version of drt lib as INV is missed in previous version

- server/src/main/scala/services/exports/flights/templates/FlightsWithSplitsExport.scala
- server/src/test/scala/controllers/ArrivalGenerator.scala
- server/src/test/scala/services/ArrivalSpec.scala
- shared/src/main/scala/drt/shared/api/Arrival.scala
Add `Difference from scheduled` column to the non-cedat arrivals exports, giving the minutes difference between the landing time and the scheduled time
> Drtii 941 improve arrivals export

- .gitignore
- project/Settings.scala
Remove spark libs which are no longer required. This removes the dependency on log4j
> DRTII-955 Remove spark libs and fix .gitignore

- server/src/main/scala/services/crunch/deskrecs/DynamicRunnableDeskRecs.scala
- server/src/test/scala/services/crunch/deskrecs/DynamicRunnableDeskRecsSpec.scala
- When live does not meet threshold test, we should add historic rather than replace so that we can still report the live API data we got
> DRTII-958 Keep live API when adding historic

- server/src/main/scala/drt/server/feeds/api/ApiFeed.scala
- server/src/main/scala/drt/server/feeds/api/ManifestProcessor.scala
- server/src/test/scala/drt/server/feeds/api/ApiFeedImplTest.scala
Send an empty `ManifestFeedSuccess` when there are no new manifests to process
> DRTII-982 Send manifestfeedsuccess on no new data

- server/src/main/scala/controllers/Application.scala
- server/src/main/scala/controllers/application/WithExports.scala
- server/src/main/scala/services/exports/Forecast.scala
- server/src/test/scala/services/ForecastHeadlineFiguresSpec.scala
- server/src/test/scala/services/crunch/PortStateSummariesSpec.scala
- shared/src/main/scala/drt/shared/PortState.scala
Don't assume days are 1440 minutes
Lean on `addDay` to correctly calculate days across clock changes
> DRTII-983 Implement clock change aware crunch summaries

- project/Settings.scala
- server/src/main/scala/drt/server/feeds/ltn/LtnLiveFeed.scala
Update the name of the touchdown time field in the LTN live feed
Bump drt-lib to update LTN config to not include the estimated chox time
> Drtii 989 investigate ltn live feed issue

- client/src/main/scala/drt/client/components/AlertsComponent.scala
- client/src/main/scala/drt/client/components/FlightComponents.scala
- e2e/tests/integration/alerts-system.ts
- e2e/tests/integration/api-splits.ts
- e2e/tests/integration/arrival-api-with-exports.ts
- e2e/tests/integration/arrivals-page.ts
- e2e/tests/integration/cedat-arrival-export.ts
- e2e/tests/integration/simulation-export.ts
- e2e/tests/integration/terminal-dashboard.ts
- e2e/tests/support/commands.ts
- server/src/main/scala/actors/daily/TerminalDayFlightActor.scala
- server/src/main/scala/actors/routing/FlightsRouterActor.scala
- server/src/main/scala/services/crunch/deskrecs/DynamicRunnableDeskRecs.scala
- server/src/test/scala/actors/PartitionedPortStateTestActor.scala
- server/src/test/scala/services/crunch/ForecastCrunchSpec.scala
- server/src/test/scala/services/crunch/deskrecs/RunnableDeskRecsSpec.scala
- shared/src/main/scala/drt/shared/FlightApi.scala
Send only the historic api pax figures for persisting rather than the whole arrival to avoid race condition with incoming arrival feeds
Fix e2e tests after large css refactor
> Drtii 797 fix historic api pax update mechanism

- project/Settings.scala
- server/src/main/scala/queueus/DynamicQueueStatusProvider.scala
Use new `queuesByTerminalWithDiversions` function to get correct queue status for diverted queues
> Drtii 1037 resolve single queue desk rec errors

- server/src/main/scala/actors/DrtSystemInterface.scala
- server/src/main/scala/services/staffing/StaffMinutesChecker.scala
- server/src/test/scala/services/crunch/CrunchGraphInputsAndProbes.scala
- server/src/test/scala/services/crunch/CrunchTestLike.scala
- server/src/test/scala/services/crunch/TestDrtActor.scala
- server/src/test/scala/services/staffing/StaffMinutesCheckerSpec.scala
Simplify staff checker to only request the last 2 days of the forecast to be recalculated without checking if there are already existing minutes as a day can contain partial minutes from the day before resulting in the day being skipped - the cause of the bug
> Drtii 1160 missing misc staff in lhr recommendations

- client/src/main/scala/drt/client/components/FlightTableComponents.scala
- client/src/main/scala/drt/client/components/FlightTableContent.scala
- server/src/main/scala/services/exports/PassengerExports.scala
- server/src/main/scala/services/exports/flights/templates/FlightsExport.scala
- server/src/main/scala/services/graphstages/DynamicWorkloadCalculator.scala
- server/src/test/scala/services/CodeSharesSpec.scala
- shared/src/main/scala/drt/shared/CodeShares.scala
Code share detection now uses the presence of live API splits as detector of main flight, followed by highest pax nos
> Drtii 1301 api data not matched at gla for ek0027 qf8027

- server/src/main/scala/drt/server/feeds/api/ApiFeed.scala
- server/src/main/scala/drt/server/feeds/api/ManifestArrivalKeys.scala
Move throttle so that it takes effect after we've filtered out zip files that didn't contain manifests for the running port
> DRTII-1454 Move throttle to after manifests have been filtered

- server/src/main/scala/drt/server/feeds/api/ApiFeed.scala
Without the throttle the db is being query constantly and thus overloaded
> DRTII-1454 Reintroduce a db query throttle

- server/src/main/scala/actors/PartitionedPortStateActor.scala
- server/src/main/scala/actors/daily/TerminalDayFlightActor.scala
- server/src/main/scala/manifests/ManifestLookup.scala
- server/src/main/scala/services/arrivals/RunnableHistoricManifestsLike.scala
- server/src/main/scala/services/arrivals/RunnableHistoricPax.scala
- server/src/main/scala/services/arrivals/RunnableHistoricSplits.scala
- server/src/main/scala/services/crunch/CrunchSystem.scala
- server/src/main/scala/slickdb/Tables.scala
- server/src/main/scala/uk/gov/homeoffice/drt/service/ApplicationService.scala
- server/src/test/scala/actors/PartitionedPortStateTestActor.scala
- server/src/test/scala/drt/server/feeds/api/DbHelper.scala
- server/src/test/scala/manifests/ManifestLookupSpec.scala
- server/src/test/scala/services/crunch/ApiPaxNosCrunchSpec.scala
- server/src/test/scala/services/crunch/CrunchTestLike.scala
- server/src/test/scala/services/crunch/TestDrtActor.scala
Increase historic manifest & pax queue buffers to fit more than 6 months of requests
Refactor some common code
Increase breadth of same flight query to include up to 3 weeks ago so we're taking an average rather than looking at a single flight
> Drtii 1472 historic api not showing

- server/src/main/scala/controllers/application/AuthController.scala
- server/src/main/scala/controllers/application/SimulationsController.scala
- server/src/main/scala/controllers/application/exports/DesksExportController.scala
- server/src/main/scala/services/exports/StreamingDesksExport.scala
- server/src/test/scala/services/OptimiserInputSpec.scala
- server/src/test/scala/services/exports/StreamingDesksBstExportSpec.scala
- server/src/test/scala/services/exports/StreamingDesksExportSpec.scala
Add optional query string parameter `period-minutes` to specify the granularity of the desks and queues exports
> DRTII-1524 Add period-minutes query string option

- client/src/main/scala/drt/client/components/Navbar.scala
- project/Settings.scala
Update drt-lib
Use port logout link from the shared `Urls.logoutUrlForPort` function
> DRTII-1541 Update drt-lib for new keycloak logout url

- client/src/main/scala/drt/client/components/FlightTableContent.scala
- Removing tooltip for RAG status as with data quality we don't need it anymore
> Remove split queue tooltip

- client/src/main/scala/drt/client/components/TerminalDesksAndQueues.scala
- server/src/main/assets/stylesheets/main.less
Set the `controls-radio-wrapper` width:
- Simplifies css
- Makes css more robust for future content changes
> DRTII-1566 smaller change with less css

- client/src/main/scala/drt/client/components/EgatesScheduleEditor.scala
> DRTII-1695 Increase max egate bank size to 15 from 10

- server/src/main/scala/services/arrivals/MergeArrivals.scala
- server/src/test/scala/services/arrivals/MergeArrivalsSpec.scala
Preserve cirium status if port live status is empty
> DRTII-1750 take new status if current one is empty

- server/src/main/scala/drt/server/feeds/AzinqFeed.scala
- server/src/test/scala/drt/server/feeds/edi/AzinqEdiFeedSpec.scala
- to ignore the invalid json object rather than whole request for array of json for edi live feed.
> Drtii 1895 edi live feed

- client/src/main/scala/drt/client/components/QueueChartComponent.scala
- server/src/main/scala/services/crunch/desklimits/PortDeskLimits.scala
- server/src/main/scala/services/crunch/desklimits/TerminalDeskLimitsLike.scala
- server/src/main/scala/services/crunch/desklimits/fixed/FixedTerminalDeskLimits.scala
- server/src/main/scala/services/crunch/desklimits/flexed/FlexedTerminalDeskLimits.scala
- server/src/main/scala/services/crunch/desklimits/flexed/FlexedTerminalDeskLimitsFromAvailableStaff.scala
- server/src/main/scala/services/crunch/deskrecs/DynamicRunnableDeployments.scala
- server/src/main/scala/services/crunch/deskrecs/PortDesksAndWaitsProvider.scala
- server/src/test/scala/drt/shared/SimulationMinuteSpec.scala
- server/src/test/scala/services/crunch/desklimits/fixed/FixedTerminalDeskLimitsSpec.scala
- server/src/test/scala/services/crunch/desklimits/flexed/FlexedTerminalDeskLimitsFromAvailableStaffSpec.scala
- server/src/test/scala/services/crunch/desklimits/flexed/FlexedTerminalDeskLimitsSpec.scala
- server/src/test/scala/services/crunch/deskrecs/DeskFlexingSpec.scala
- server/src/test/scala/services/crunch/deskrecs/PortDesksAndWaitsProviderSpec.scala
- shared/src/main/scala/drt/shared/SimulationMinute.scala
Use date to determine queues with minimum desks
Record deployment specific pax in queues
Display deployment specific pax in queues in desks and queues charts
> Drtii 1928 false wait times
